// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.demo.protobuf;

public final class MessageBuf {
    private MessageBuf() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 消息内容
         * </pre>
         * <p>
         * <code>optional string msg = 1;</code>
         */
        String getMsg();

        /**
         * <pre>
         * 消息内容
         * </pre>
         * <p>
         * <code>optional string msg = 1;</code>
         */
        com.google.protobuf.ByteString getMsgBytes();

        /**
         * <pre>
         * 消息类型
         * </pre>
         * <p>
         * <code>optional int64 type = 2;</code>
         */
        long getType();

        /**
         * <pre>
         * 经度
         * </pre>
         * <p>
         * <code>optional double lon = 3;</code>
         */
        double getLon();

        /**
         * <pre>
         * 纬度
         * </pre>
         * <p>
         * <code>optional double lat = 4;</code>
         */
        double getLat();
    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Message extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            msg_ = "";
            type_ = 0L;
            lon_ = 0D;
            lat_ = 0D;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Message(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        case 16: {

                            type_ = input.readInt64();
                            break;
                        }
                        case 25: {

                            lon_ = input.readDouble();
                            break;
                        }
                        case 33: {

                            lat_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.demo.protobuf.MessageBuf.internal_static_Message_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.demo.protobuf.MessageBuf.internal_static_Message_fieldAccessorTable.ensureFieldAccessorsInitialized(com.demo.protobuf.MessageBuf.Message.class, com.demo.protobuf.MessageBuf.Message.Builder.class);
        }

        public static final int MSG_FIELD_NUMBER = 1;
        private volatile Object msg_;

        /**
         * <pre>
         * 消息内容
         * </pre>
         * <p>
         * <code>optional string msg = 1;</code>
         */
        public String getMsg() {
            Object ref = msg_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 消息内容
         * </pre>
         * <p>
         * <code>optional string msg = 1;</code>
         */
        public com.google.protobuf.ByteString getMsgBytes() {
            Object ref = msg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private long type_;

        /**
         * <pre>
         * 消息类型
         * </pre>
         * <p>
         * <code>optional int64 type = 2;</code>
         */
        public long getType() {
            return type_;
        }

        public static final int LON_FIELD_NUMBER = 3;
        private double lon_;

        /**
         * <pre>
         * 经度
         * </pre>
         * <p>
         * <code>optional double lon = 3;</code>
         */
        public double getLon() {
            return lon_;
        }

        public static final int LAT_FIELD_NUMBER = 4;
        private double lat_;

        /**
         * <pre>
         * 纬度
         * </pre>
         * <p>
         * <code>optional double lat = 4;</code>
         */
        public double getLat() {
            return lat_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getMsgBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
            }
            if (type_ != 0L) {
                output.writeInt64(2, type_);
            }
            if (lon_ != 0D) {
                output.writeDouble(3, lon_);
            }
            if (lat_ != 0D) {
                output.writeDouble(4, lat_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!getMsgBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
            }
            if (type_ != 0L) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, type_);
            }
            if (lon_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(3, lon_);
            }
            if (lat_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(4, lat_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.demo.protobuf.MessageBuf.Message)) {
                return super.equals(obj);
            }
            com.demo.protobuf.MessageBuf.Message other = (com.demo.protobuf.MessageBuf.Message) obj;

            boolean result = true;
            result = result && getMsg().equals(other.getMsg());
            result = result && (getType() == other.getType());
            result = result && (Double.doubleToLongBits(getLon()) == Double.doubleToLongBits(other.getLon()));
            result = result && (Double.doubleToLongBits(getLat()) == Double.doubleToLongBits(other.getLat()));
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getType());
            hash = (37 * hash) + LON_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getLon()));
            hash = (37 * hash) + LAT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getLat()));
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.demo.protobuf.MessageBuf.Message parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static com.demo.protobuf.MessageBuf.Message parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static com.demo.protobuf.MessageBuf.Message parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.demo.protobuf.MessageBuf.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Message}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                com.demo.protobuf.MessageBuf.MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return com.demo.protobuf.MessageBuf.internal_static_Message_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return com.demo.protobuf.MessageBuf.internal_static_Message_fieldAccessorTable.ensureFieldAccessorsInitialized(com.demo.protobuf.MessageBuf.Message.class, com.demo.protobuf.MessageBuf.Message.Builder.class);
            }

            // Construct using com.demo.protobuf.MessageBuf.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                msg_ = "";

                type_ = 0L;

                lon_ = 0D;

                lat_ = 0D;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return com.demo.protobuf.MessageBuf.internal_static_Message_descriptor;
            }

            public com.demo.protobuf.MessageBuf.Message getDefaultInstanceForType() {
                return com.demo.protobuf.MessageBuf.Message.getDefaultInstance();
            }

            public com.demo.protobuf.MessageBuf.Message build() {
                com.demo.protobuf.MessageBuf.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.demo.protobuf.MessageBuf.Message buildPartial() {
                com.demo.protobuf.MessageBuf.Message result = new com.demo.protobuf.MessageBuf.Message(this);
                result.msg_ = msg_;
                result.type_ = type_;
                result.lon_ = lon_;
                result.lat_ = lat_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.demo.protobuf.MessageBuf.Message) {
                    return mergeFrom((com.demo.protobuf.MessageBuf.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.demo.protobuf.MessageBuf.Message other) {
                if (other == com.demo.protobuf.MessageBuf.Message.getDefaultInstance())
                    return this;
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                if (other.getType() != 0L) {
                    setType(other.getType());
                }
                if (other.getLon() != 0D) {
                    setLon(other.getLon());
                }
                if (other.getLat() != 0D) {
                    setLat(other.getLat());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                com.demo.protobuf.MessageBuf.Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.demo.protobuf.MessageBuf.Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Object msg_ = "";

            /**
             * <pre>
             * 消息内容
             * </pre>
             * <p>
             * <code>optional string msg = 1;</code>
             */
            public String getMsg() {
                Object ref = msg_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 消息内容
             * </pre>
             * <p>
             * <code>optional string msg = 1;</code>
             */
            public com.google.protobuf.ByteString getMsgBytes() {
                Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 消息内容
             * </pre>
             * <p>
             * <code>optional string msg = 1;</code>
             */
            public Builder setMsg(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息内容
             * </pre>
             * <p>
             * <code>optional string msg = 1;</code>
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息内容
             * </pre>
             * <p>
             * <code>optional string msg = 1;</code>
             */
            public Builder setMsgBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            private long type_;

            /**
             * <pre>
             * 消息类型
             * </pre>
             * <p>
             * <code>optional int64 type = 2;</code>
             */
            public long getType() {
                return type_;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             * <p>
             * <code>optional int64 type = 2;</code>
             */
            public Builder setType(long value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             * <p>
             * <code>optional int64 type = 2;</code>
             */
            public Builder clearType() {

                type_ = 0L;
                onChanged();
                return this;
            }

            private double lon_;

            /**
             * <pre>
             * 经度
             * </pre>
             * <p>
             * <code>optional double lon = 3;</code>
             */
            public double getLon() {
                return lon_;
            }

            /**
             * <pre>
             * 经度
             * </pre>
             * <p>
             * <code>optional double lon = 3;</code>
             */
            public Builder setLon(double value) {

                lon_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 经度
             * </pre>
             * <p>
             * <code>optional double lon = 3;</code>
             */
            public Builder clearLon() {

                lon_ = 0D;
                onChanged();
                return this;
            }

            private double lat_;

            /**
             * <pre>
             * 纬度
             * </pre>
             * <p>
             * <code>optional double lat = 4;</code>
             */
            public double getLat() {
                return lat_;
            }

            /**
             * <pre>
             * 纬度
             * </pre>
             * <p>
             * <code>optional double lat = 4;</code>
             */
            public Builder setLat(double value) {

                lat_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 纬度
             * </pre>
             * <p>
             * <code>optional double lat = 4;</code>
             */
            public Builder clearLat() {

                lat_ = 0D;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:Message)
        }

        // @@protoc_insertion_point(class_scope:Message)
        private static final com.demo.protobuf.MessageBuf.Message DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.demo.protobuf.MessageBuf.Message();
        }

        public static com.demo.protobuf.MessageBuf.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Message> PARSER = new com.google.protobuf.AbstractParser<Message>() {
            public Message parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        public com.demo.protobuf.MessageBuf.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Message_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Message_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\rMessage.proto\">\n\007Message\022\013\n\003msg\030\001 \001(\t\022" + "\014\n\004type\030\002 \001(\003\022\013\n\003lon\030\003 \001(\001\022\013\n\003lat\030\004 \001(\001B" + "\033\n\rcom.demo.protobufB\nMessageBufb\006proto3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
        internal_static_Message_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Message_descriptor, new String[]{"Msg", "Type", "Lon", "Lat",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
