// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ape.proto

package com.kedacom.ctsp.cvf.viid.common.protobuf;

public final class APEProtobuf {
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_APE_Proto_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_APE_Proto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\tape.proto\"\321\002\n\tAPE_Proto\022\r\n\005APEID\030\001 \001(\t"
            + "\022\014\n\004Name\030\002 \001(\t\022\r\n\005Model\030\003 \001(\t\022\016\n\006IPAddr\030"
            + "\004 \001(\t\022\020\n\010IPv6Addr\030\005 \001(\t\022\014\n\004Port\030\006 \001(\005\022\022\n"
            + "\nLongtitude\030\007 \001(\001\022\020\n\010Latitude\030\010 \001(\001\022\021\n\tP"
            + "laceCode\030\t \001(\t\022\r\n\005Place\030\n \001(\t\022\017\n\007OrgCode"
            + "\030\013 \001(\t\022\024\n\014CapDirection\030\014 \001(\005\022\030\n\020MonitorD"
            + "irection\030\r \001(\t\022\027\n\017MonitorAreaDesc\030\016 \001(\t\022"
            + "\020\n\010IsOnline\030\017 \001(\005\022\022\n\nOwnerApsID\030\020 \001(\t\022\016\n"
            + "\006UserId\030\021 \001(\t\022\020\n\010Password\030\022 \001(\tB8\n)com.k"
            + "edacom.ctsp.cvf.viid.common.protobufB\013AP" + "EProtobufb\006proto3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry
                    assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_APE_Proto_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_APE_Proto_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_APE_Proto_descriptor,
                new String[] {"APEID", "Name", "Model", "IPAddr", "IPv6Addr", "Port", "Longtitude", "Latitude",
                    "PlaceCode", "Place", "OrgCode", "CapDirection", "MonitorDirection", "MonitorAreaDesc", "IsOnline",
                    "OwnerApsID", "UserId", "Password",});
    }

    private APEProtobuf() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite)registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    public interface APE_ProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:APE_Proto)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string APEID = 1;</code>
         */
        String getAPEID();

        /**
         * <code>string APEID = 1;</code>
         */
        com.google.protobuf.ByteString getAPEIDBytes();

        /**
         * <code>string Name = 2;</code>
         */
        String getName();

        /**
         * <code>string Name = 2;</code>
         */
        com.google.protobuf.ByteString getNameBytes();

        /**
         * <code>string Model = 3;</code>
         */
        String getModel();

        /**
         * <code>string Model = 3;</code>
         */
        com.google.protobuf.ByteString getModelBytes();

        /**
         * <code>string IPAddr = 4;</code>
         */
        String getIPAddr();

        /**
         * <code>string IPAddr = 4;</code>
         */
        com.google.protobuf.ByteString getIPAddrBytes();

        /**
         * <code>string IPv6Addr = 5;</code>
         */
        String getIPv6Addr();

        /**
         * <code>string IPv6Addr = 5;</code>
         */
        com.google.protobuf.ByteString getIPv6AddrBytes();

        /**
         * <code>int32 Port = 6;</code>
         */
        int getPort();

        /**
         * <code>double Longtitude = 7;</code>
         */
        double getLongtitude();

        /**
         * <code>double Latitude = 8;</code>
         */
        double getLatitude();

        /**
         * <code>string PlaceCode = 9;</code>
         */
        String getPlaceCode();

        /**
         * <code>string PlaceCode = 9;</code>
         */
        com.google.protobuf.ByteString getPlaceCodeBytes();

        /**
         * <code>string Place = 10;</code>
         */
        String getPlace();

        /**
         * <code>string Place = 10;</code>
         */
        com.google.protobuf.ByteString getPlaceBytes();

        /**
         * <code>string OrgCode = 11;</code>
         */
        String getOrgCode();

        /**
         * <code>string OrgCode = 11;</code>
         */
        com.google.protobuf.ByteString getOrgCodeBytes();

        /**
         * <code>int32 CapDirection = 12;</code>
         */
        int getCapDirection();

        /**
         * <code>string MonitorDirection = 13;</code>
         */
        String getMonitorDirection();

        /**
         * <code>string MonitorDirection = 13;</code>
         */
        com.google.protobuf.ByteString getMonitorDirectionBytes();

        /**
         * <code>string MonitorAreaDesc = 14;</code>
         */
        String getMonitorAreaDesc();

        /**
         * <code>string MonitorAreaDesc = 14;</code>
         */
        com.google.protobuf.ByteString getMonitorAreaDescBytes();

        /**
         * <code>int32 IsOnline = 15;</code>
         */
        int getIsOnline();

        /**
         * <code>string OwnerApsID = 16;</code>
         */
        String getOwnerApsID();

        /**
         * <code>string OwnerApsID = 16;</code>
         */
        com.google.protobuf.ByteString getOwnerApsIDBytes();

        /**
         * <code>string UserId = 17;</code>
         */
        String getUserId();

        /**
         * <code>string UserId = 17;</code>
         */
        com.google.protobuf.ByteString getUserIdBytes();

        /**
         * <code>string Password = 18;</code>
         */
        String getPassword();

        /**
         * <code>string Password = 18;</code>
         */
        com.google.protobuf.ByteString getPasswordBytes();
    }

    /**
     * Protobuf type {@code APE_Proto}
     */
    public static final class APE_Proto extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:APE_Proto)
        APE_ProtoOrBuilder {
        public static final int APEID_FIELD_NUMBER = 1;
        public static final int NAME_FIELD_NUMBER = 2;
        public static final int MODEL_FIELD_NUMBER = 3;
        public static final int IPADDR_FIELD_NUMBER = 4;
        public static final int IPV6ADDR_FIELD_NUMBER = 5;
        public static final int PORT_FIELD_NUMBER = 6;
        public static final int LONGTITUDE_FIELD_NUMBER = 7;
        public static final int LATITUDE_FIELD_NUMBER = 8;
        public static final int PLACECODE_FIELD_NUMBER = 9;
        public static final int PLACE_FIELD_NUMBER = 10;
        public static final int ORGCODE_FIELD_NUMBER = 11;
        public static final int CAPDIRECTION_FIELD_NUMBER = 12;
        public static final int MONITORDIRECTION_FIELD_NUMBER = 13;
        public static final int MONITORAREADESC_FIELD_NUMBER = 14;
        public static final int ISONLINE_FIELD_NUMBER = 15;
        public static final int OWNERAPSID_FIELD_NUMBER = 16;
        public static final int USERID_FIELD_NUMBER = 17;
        public static final int PASSWORD_FIELD_NUMBER = 18;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:APE_Proto)
        private static final APE_Proto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<APE_Proto> PARSER =
            new com.google.protobuf.AbstractParser<APE_Proto>() {
                public APE_Proto parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new APE_Proto(input, extensionRegistry);
                }
            };

        static {
            DEFAULT_INSTANCE = new APE_Proto();
        }

        private volatile Object aPEID_;
        private volatile Object name_;
        private volatile Object model_;
        private volatile Object iPAddr_;
        private volatile Object iPv6Addr_;
        private int port_;
        private double longtitude_;
        private double latitude_;
        private volatile Object placeCode_;
        private volatile Object place_;
        private volatile Object orgCode_;
        private int capDirection_;
        private volatile Object monitorDirection_;
        private volatile Object monitorAreaDesc_;
        private int isOnline_;
        private volatile Object ownerApsID_;
        private volatile Object userId_;
        private volatile Object password_;
        private byte memoizedIsInitialized = -1;

        // Use APE_Proto.newBuilder() to construct.
        private APE_Proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private APE_Proto() {
            aPEID_ = "";
            name_ = "";
            model_ = "";
            iPAddr_ = "";
            iPv6Addr_ = "";
            port_ = 0;
            longtitude_ = 0D;
            latitude_ = 0D;
            placeCode_ = "";
            place_ = "";
            orgCode_ = "";
            capDirection_ = 0;
            monitorDirection_ = "";
            monitorAreaDesc_ = "";
            isOnline_ = 0;
            ownerApsID_ = "";
            userId_ = "";
            password_ = "";
        }

        private APE_Proto(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            aPEID_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            model_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            iPAddr_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            iPv6Addr_ = s;
                            break;
                        }
                        case 48: {

                            port_ = input.readInt32();
                            break;
                        }
                        case 57: {

                            longtitude_ = input.readDouble();
                            break;
                        }
                        case 65: {

                            latitude_ = input.readDouble();
                            break;
                        }
                        case 74: {
                            String s = input.readStringRequireUtf8();

                            placeCode_ = s;
                            break;
                        }
                        case 82: {
                            String s = input.readStringRequireUtf8();

                            place_ = s;
                            break;
                        }
                        case 90: {
                            String s = input.readStringRequireUtf8();

                            orgCode_ = s;
                            break;
                        }
                        case 96: {

                            capDirection_ = input.readInt32();
                            break;
                        }
                        case 106: {
                            String s = input.readStringRequireUtf8();

                            monitorDirection_ = s;
                            break;
                        }
                        case 114: {
                            String s = input.readStringRequireUtf8();

                            monitorAreaDesc_ = s;
                            break;
                        }
                        case 120: {

                            isOnline_ = input.readInt32();
                            break;
                        }
                        case 130: {
                            String s = input.readStringRequireUtf8();

                            ownerApsID_ = s;
                            break;
                        }
                        case 138: {
                            String s = input.readStringRequireUtf8();

                            userId_ = s;
                            break;
                        }
                        case 146: {
                            String s = input.readStringRequireUtf8();

                            password_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return APEProtobuf.internal_static_APE_Proto_descriptor;
        }

        public static APE_Proto parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APE_Proto parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APE_Proto parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APE_Proto parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APE_Proto parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static APE_Proto parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static APE_Proto parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static APE_Proto parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static APE_Proto parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static APE_Proto parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static APE_Proto parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static APE_Proto parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(APE_Proto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static APE_Proto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<APE_Proto> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return APEProtobuf.internal_static_APE_Proto_fieldAccessorTable
                .ensureFieldAccessorsInitialized(APE_Proto.class, Builder.class);
        }

        /**
         * <code>string APEID = 1;</code>
         */
        public String getAPEID() {
            Object ref = aPEID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                aPEID_ = s;
                return s;
            }
        }

        /**
         * <code>string APEID = 1;</code>
         */
        public com.google.protobuf.ByteString getAPEIDBytes() {
            Object ref = aPEID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                aPEID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Name = 2;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string Name = 2;</code>
         */
        public com.google.protobuf.ByteString getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Model = 3;</code>
         */
        public String getModel() {
            Object ref = model_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                model_ = s;
                return s;
            }
        }

        /**
         * <code>string Model = 3;</code>
         */
        public com.google.protobuf.ByteString getModelBytes() {
            Object ref = model_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                model_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string IPAddr = 4;</code>
         */
        public String getIPAddr() {
            Object ref = iPAddr_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                iPAddr_ = s;
                return s;
            }
        }

        /**
         * <code>string IPAddr = 4;</code>
         */
        public com.google.protobuf.ByteString getIPAddrBytes() {
            Object ref = iPAddr_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                iPAddr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string IPv6Addr = 5;</code>
         */
        public String getIPv6Addr() {
            Object ref = iPv6Addr_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                iPv6Addr_ = s;
                return s;
            }
        }

        /**
         * <code>string IPv6Addr = 5;</code>
         */
        public com.google.protobuf.ByteString getIPv6AddrBytes() {
            Object ref = iPv6Addr_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                iPv6Addr_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int32 Port = 6;</code>
         */
        public int getPort() {
            return port_;
        }

        /**
         * <code>double Longtitude = 7;</code>
         */
        public double getLongtitude() {
            return longtitude_;
        }

        /**
         * <code>double Latitude = 8;</code>
         */
        public double getLatitude() {
            return latitude_;
        }

        /**
         * <code>string PlaceCode = 9;</code>
         */
        public String getPlaceCode() {
            Object ref = placeCode_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                placeCode_ = s;
                return s;
            }
        }

        /**
         * <code>string PlaceCode = 9;</code>
         */
        public com.google.protobuf.ByteString getPlaceCodeBytes() {
            Object ref = placeCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                placeCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Place = 10;</code>
         */
        public String getPlace() {
            Object ref = place_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                place_ = s;
                return s;
            }
        }

        /**
         * <code>string Place = 10;</code>
         */
        public com.google.protobuf.ByteString getPlaceBytes() {
            Object ref = place_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                place_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string OrgCode = 11;</code>
         */
        public String getOrgCode() {
            Object ref = orgCode_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                orgCode_ = s;
                return s;
            }
        }

        /**
         * <code>string OrgCode = 11;</code>
         */
        public com.google.protobuf.ByteString getOrgCodeBytes() {
            Object ref = orgCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                orgCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int32 CapDirection = 12;</code>
         */
        public int getCapDirection() {
            return capDirection_;
        }

        /**
         * <code>string MonitorDirection = 13;</code>
         */
        public String getMonitorDirection() {
            Object ref = monitorDirection_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                monitorDirection_ = s;
                return s;
            }
        }

        /**
         * <code>string MonitorDirection = 13;</code>
         */
        public com.google.protobuf.ByteString getMonitorDirectionBytes() {
            Object ref = monitorDirection_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                monitorDirection_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string MonitorAreaDesc = 14;</code>
         */
        public String getMonitorAreaDesc() {
            Object ref = monitorAreaDesc_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                monitorAreaDesc_ = s;
                return s;
            }
        }

        /**
         * <code>string MonitorAreaDesc = 14;</code>
         */
        public com.google.protobuf.ByteString getMonitorAreaDescBytes() {
            Object ref = monitorAreaDesc_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                monitorAreaDesc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int32 IsOnline = 15;</code>
         */
        public int getIsOnline() {
            return isOnline_;
        }

        /**
         * <code>string OwnerApsID = 16;</code>
         */
        public String getOwnerApsID() {
            Object ref = ownerApsID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                ownerApsID_ = s;
                return s;
            }
        }

        /**
         * <code>string OwnerApsID = 16;</code>
         */
        public com.google.protobuf.ByteString getOwnerApsIDBytes() {
            Object ref = ownerApsID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                ownerApsID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string UserId = 17;</code>
         */
        public String getUserId() {
            Object ref = userId_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                userId_ = s;
                return s;
            }
        }

        /**
         * <code>string UserId = 17;</code>
         */
        public com.google.protobuf.ByteString getUserIdBytes() {
            Object ref = userId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                userId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Password = 18;</code>
         */
        public String getPassword() {
            Object ref = password_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                password_ = s;
                return s;
            }
        }

        /**
         * <code>string Password = 18;</code>
         */
        public com.google.protobuf.ByteString getPasswordBytes() {
            Object ref = password_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getAPEIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aPEID_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (!getModelBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, model_);
            }
            if (!getIPAddrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, iPAddr_);
            }
            if (!getIPv6AddrBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, iPv6Addr_);
            }
            if (port_ != 0) {
                output.writeInt32(6, port_);
            }
            if (longtitude_ != 0D) {
                output.writeDouble(7, longtitude_);
            }
            if (latitude_ != 0D) {
                output.writeDouble(8, latitude_);
            }
            if (!getPlaceCodeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 9, placeCode_);
            }
            if (!getPlaceBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 10, place_);
            }
            if (!getOrgCodeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 11, orgCode_);
            }
            if (capDirection_ != 0) {
                output.writeInt32(12, capDirection_);
            }
            if (!getMonitorDirectionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 13, monitorDirection_);
            }
            if (!getMonitorAreaDescBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 14, monitorAreaDesc_);
            }
            if (isOnline_ != 0) {
                output.writeInt32(15, isOnline_);
            }
            if (!getOwnerApsIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 16, ownerApsID_);
            }
            if (!getUserIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 17, userId_);
            }
            if (!getPasswordBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 18, password_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!getAPEIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aPEID_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (!getModelBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, model_);
            }
            if (!getIPAddrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, iPAddr_);
            }
            if (!getIPv6AddrBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, iPv6Addr_);
            }
            if (port_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(6, port_);
            }
            if (longtitude_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(7, longtitude_);
            }
            if (latitude_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(8, latitude_);
            }
            if (!getPlaceCodeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, placeCode_);
            }
            if (!getPlaceBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, place_);
            }
            if (!getOrgCodeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, orgCode_);
            }
            if (capDirection_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(12, capDirection_);
            }
            if (!getMonitorDirectionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, monitorDirection_);
            }
            if (!getMonitorAreaDescBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, monitorAreaDesc_);
            }
            if (isOnline_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(15, isOnline_);
            }
            if (!getOwnerApsIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, ownerApsID_);
            }
            if (!getUserIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, userId_);
            }
            if (!getPasswordBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, password_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof APE_Proto)) {
                return super.equals(obj);
            }
            APE_Proto other = (APE_Proto)obj;

            boolean result = true;
            result = result && getAPEID().equals(other.getAPEID());
            result = result && getName().equals(other.getName());
            result = result && getModel().equals(other.getModel());
            result = result && getIPAddr().equals(other.getIPAddr());
            result = result && getIPv6Addr().equals(other.getIPv6Addr());
            result = result && (getPort() == other.getPort());
            result =
                result && (Double.doubleToLongBits(getLongtitude()) == Double.doubleToLongBits(other.getLongtitude()));
            result = result && (Double.doubleToLongBits(getLatitude()) == Double.doubleToLongBits(other.getLatitude()));
            result = result && getPlaceCode().equals(other.getPlaceCode());
            result = result && getPlace().equals(other.getPlace());
            result = result && getOrgCode().equals(other.getOrgCode());
            result = result && (getCapDirection() == other.getCapDirection());
            result = result && getMonitorDirection().equals(other.getMonitorDirection());
            result = result && getMonitorAreaDesc().equals(other.getMonitorAreaDesc());
            result = result && (getIsOnline() == other.getIsOnline());
            result = result && getOwnerApsID().equals(other.getOwnerApsID());
            result = result && getUserId().equals(other.getUserId());
            result = result && getPassword().equals(other.getPassword());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + APEID_FIELD_NUMBER;
            hash = (53 * hash) + getAPEID().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + MODEL_FIELD_NUMBER;
            hash = (53 * hash) + getModel().hashCode();
            hash = (37 * hash) + IPADDR_FIELD_NUMBER;
            hash = (53 * hash) + getIPAddr().hashCode();
            hash = (37 * hash) + IPV6ADDR_FIELD_NUMBER;
            hash = (53 * hash) + getIPv6Addr().hashCode();
            hash = (37 * hash) + PORT_FIELD_NUMBER;
            hash = (53 * hash) + getPort();
            hash = (37 * hash) + LONGTITUDE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getLongtitude()));
            hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getLatitude()));
            hash = (37 * hash) + PLACECODE_FIELD_NUMBER;
            hash = (53 * hash) + getPlaceCode().hashCode();
            hash = (37 * hash) + PLACE_FIELD_NUMBER;
            hash = (53 * hash) + getPlace().hashCode();
            hash = (37 * hash) + ORGCODE_FIELD_NUMBER;
            hash = (53 * hash) + getOrgCode().hashCode();
            hash = (37 * hash) + CAPDIRECTION_FIELD_NUMBER;
            hash = (53 * hash) + getCapDirection();
            hash = (37 * hash) + MONITORDIRECTION_FIELD_NUMBER;
            hash = (53 * hash) + getMonitorDirection().hashCode();
            hash = (37 * hash) + MONITORAREADESC_FIELD_NUMBER;
            hash = (53 * hash) + getMonitorAreaDesc().hashCode();
            hash = (37 * hash) + ISONLINE_FIELD_NUMBER;
            hash = (53 * hash) + getIsOnline();
            hash = (37 * hash) + OWNERAPSID_FIELD_NUMBER;
            hash = (53 * hash) + getOwnerApsID().hashCode();
            hash = (37 * hash) + USERID_FIELD_NUMBER;
            hash = (53 * hash) + getUserId().hashCode();
            hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
            hash = (53 * hash) + getPassword().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<APE_Proto> getParserForType() {
            return PARSER;
        }

        public APE_Proto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code APE_Proto}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:APE_Proto)
            APE_ProtoOrBuilder {
            private Object aPEID_ = "";
            private Object name_ = "";
            private Object model_ = "";
            private Object iPAddr_ = "";
            private Object iPv6Addr_ = "";
            private int port_;
            private double longtitude_;
            private double latitude_;
            private Object placeCode_ = "";
            private Object place_ = "";
            private Object orgCode_ = "";
            private int capDirection_;
            private Object monitorDirection_ = "";
            private Object monitorAreaDesc_ = "";
            private int isOnline_;
            private Object ownerApsID_ = "";
            private Object userId_ = "";
            private Object password_ = "";

            // Construct using com.kedacom.ctsp.cvf.viid.common.protobuf.APEProtobuf.APE_Proto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return APEProtobuf.internal_static_APE_Proto_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return APEProtobuf.internal_static_APE_Proto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(APE_Proto.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                aPEID_ = "";

                name_ = "";

                model_ = "";

                iPAddr_ = "";

                iPv6Addr_ = "";

                port_ = 0;

                longtitude_ = 0D;

                latitude_ = 0D;

                placeCode_ = "";

                place_ = "";

                orgCode_ = "";

                capDirection_ = 0;

                monitorDirection_ = "";

                monitorAreaDesc_ = "";

                isOnline_ = 0;

                ownerApsID_ = "";

                userId_ = "";

                password_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return APEProtobuf.internal_static_APE_Proto_descriptor;
            }

            public APE_Proto getDefaultInstanceForType() {
                return APE_Proto.getDefaultInstance();
            }

            public APE_Proto build() {
                APE_Proto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public APE_Proto buildPartial() {
                APE_Proto result = new APE_Proto(this);
                result.aPEID_ = aPEID_;
                result.name_ = name_;
                result.model_ = model_;
                result.iPAddr_ = iPAddr_;
                result.iPv6Addr_ = iPv6Addr_;
                result.port_ = port_;
                result.longtitude_ = longtitude_;
                result.latitude_ = latitude_;
                result.placeCode_ = placeCode_;
                result.place_ = place_;
                result.orgCode_ = orgCode_;
                result.capDirection_ = capDirection_;
                result.monitorDirection_ = monitorDirection_;
                result.monitorAreaDesc_ = monitorAreaDesc_;
                result.isOnline_ = isOnline_;
                result.ownerApsID_ = ownerApsID_;
                result.userId_ = userId_;
                result.password_ = password_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder)super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder)super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder)super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                Object value) {
                return (Builder)super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof APE_Proto) {
                    return mergeFrom((APE_Proto)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(APE_Proto other) {
                if (other == APE_Proto.getDefaultInstance())
                    return this;
                if (!other.getAPEID().isEmpty()) {
                    aPEID_ = other.aPEID_;
                    onChanged();
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (!other.getModel().isEmpty()) {
                    model_ = other.model_;
                    onChanged();
                }
                if (!other.getIPAddr().isEmpty()) {
                    iPAddr_ = other.iPAddr_;
                    onChanged();
                }
                if (!other.getIPv6Addr().isEmpty()) {
                    iPv6Addr_ = other.iPv6Addr_;
                    onChanged();
                }
                if (other.getPort() != 0) {
                    setPort(other.getPort());
                }
                if (other.getLongtitude() != 0D) {
                    setLongtitude(other.getLongtitude());
                }
                if (other.getLatitude() != 0D) {
                    setLatitude(other.getLatitude());
                }
                if (!other.getPlaceCode().isEmpty()) {
                    placeCode_ = other.placeCode_;
                    onChanged();
                }
                if (!other.getPlace().isEmpty()) {
                    place_ = other.place_;
                    onChanged();
                }
                if (!other.getOrgCode().isEmpty()) {
                    orgCode_ = other.orgCode_;
                    onChanged();
                }
                if (other.getCapDirection() != 0) {
                    setCapDirection(other.getCapDirection());
                }
                if (!other.getMonitorDirection().isEmpty()) {
                    monitorDirection_ = other.monitorDirection_;
                    onChanged();
                }
                if (!other.getMonitorAreaDesc().isEmpty()) {
                    monitorAreaDesc_ = other.monitorAreaDesc_;
                    onChanged();
                }
                if (other.getIsOnline() != 0) {
                    setIsOnline(other.getIsOnline());
                }
                if (!other.getOwnerApsID().isEmpty()) {
                    ownerApsID_ = other.ownerApsID_;
                    onChanged();
                }
                if (!other.getUserId().isEmpty()) {
                    userId_ = other.userId_;
                    onChanged();
                }
                if (!other.getPassword().isEmpty()) {
                    password_ = other.password_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                APE_Proto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (APE_Proto)e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string APEID = 1;</code>
             */
            public String getAPEID() {
                Object ref = aPEID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    aPEID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string APEID = 1;</code>
             */
            public Builder setAPEID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                aPEID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string APEID = 1;</code>
             */
            public com.google.protobuf.ByteString getAPEIDBytes() {
                Object ref = aPEID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    aPEID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string APEID = 1;</code>
             */
            public Builder setAPEIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                aPEID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string APEID = 1;</code>
             */
            public Builder clearAPEID() {

                aPEID_ = getDefaultInstance().getAPEID();
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 2;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Name = 2;</code>
             */
            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 2;</code>
             */
            public com.google.protobuf.ByteString getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Name = 2;</code>
             */
            public Builder setNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>string Model = 3;</code>
             */
            public String getModel() {
                Object ref = model_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    model_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Model = 3;</code>
             */
            public Builder setModel(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                model_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Model = 3;</code>
             */
            public com.google.protobuf.ByteString getModelBytes() {
                Object ref = model_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    model_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Model = 3;</code>
             */
            public Builder setModelBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                model_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Model = 3;</code>
             */
            public Builder clearModel() {

                model_ = getDefaultInstance().getModel();
                onChanged();
                return this;
            }

            /**
             * <code>string IPAddr = 4;</code>
             */
            public String getIPAddr() {
                Object ref = iPAddr_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    iPAddr_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string IPAddr = 4;</code>
             */
            public Builder setIPAddr(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                iPAddr_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string IPAddr = 4;</code>
             */
            public com.google.protobuf.ByteString getIPAddrBytes() {
                Object ref = iPAddr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    iPAddr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string IPAddr = 4;</code>
             */
            public Builder setIPAddrBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                iPAddr_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string IPAddr = 4;</code>
             */
            public Builder clearIPAddr() {

                iPAddr_ = getDefaultInstance().getIPAddr();
                onChanged();
                return this;
            }

            /**
             * <code>string IPv6Addr = 5;</code>
             */
            public String getIPv6Addr() {
                Object ref = iPv6Addr_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    iPv6Addr_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string IPv6Addr = 5;</code>
             */
            public Builder setIPv6Addr(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                iPv6Addr_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string IPv6Addr = 5;</code>
             */
            public com.google.protobuf.ByteString getIPv6AddrBytes() {
                Object ref = iPv6Addr_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    iPv6Addr_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string IPv6Addr = 5;</code>
             */
            public Builder setIPv6AddrBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                iPv6Addr_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string IPv6Addr = 5;</code>
             */
            public Builder clearIPv6Addr() {

                iPv6Addr_ = getDefaultInstance().getIPv6Addr();
                onChanged();
                return this;
            }

            /**
             * <code>int32 Port = 6;</code>
             */
            public int getPort() {
                return port_;
            }

            /**
             * <code>int32 Port = 6;</code>
             */
            public Builder setPort(int value) {

                port_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 Port = 6;</code>
             */
            public Builder clearPort() {

                port_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>double Longtitude = 7;</code>
             */
            public double getLongtitude() {
                return longtitude_;
            }

            /**
             * <code>double Longtitude = 7;</code>
             */
            public Builder setLongtitude(double value) {

                longtitude_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double Longtitude = 7;</code>
             */
            public Builder clearLongtitude() {

                longtitude_ = 0D;
                onChanged();
                return this;
            }

            /**
             * <code>double Latitude = 8;</code>
             */
            public double getLatitude() {
                return latitude_;
            }

            /**
             * <code>double Latitude = 8;</code>
             */
            public Builder setLatitude(double value) {

                latitude_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double Latitude = 8;</code>
             */
            public Builder clearLatitude() {

                latitude_ = 0D;
                onChanged();
                return this;
            }

            /**
             * <code>string PlaceCode = 9;</code>
             */
            public String getPlaceCode() {
                Object ref = placeCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    placeCode_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string PlaceCode = 9;</code>
             */
            public Builder setPlaceCode(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                placeCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string PlaceCode = 9;</code>
             */
            public com.google.protobuf.ByteString getPlaceCodeBytes() {
                Object ref = placeCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    placeCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string PlaceCode = 9;</code>
             */
            public Builder setPlaceCodeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                placeCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string PlaceCode = 9;</code>
             */
            public Builder clearPlaceCode() {

                placeCode_ = getDefaultInstance().getPlaceCode();
                onChanged();
                return this;
            }

            /**
             * <code>string Place = 10;</code>
             */
            public String getPlace() {
                Object ref = place_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    place_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Place = 10;</code>
             */
            public Builder setPlace(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                place_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Place = 10;</code>
             */
            public com.google.protobuf.ByteString getPlaceBytes() {
                Object ref = place_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    place_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Place = 10;</code>
             */
            public Builder setPlaceBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                place_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Place = 10;</code>
             */
            public Builder clearPlace() {

                place_ = getDefaultInstance().getPlace();
                onChanged();
                return this;
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public String getOrgCode() {
                Object ref = orgCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    orgCode_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public Builder setOrgCode(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                orgCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public com.google.protobuf.ByteString getOrgCodeBytes() {
                Object ref = orgCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    orgCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public Builder setOrgCodeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                orgCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public Builder clearOrgCode() {

                orgCode_ = getDefaultInstance().getOrgCode();
                onChanged();
                return this;
            }

            /**
             * <code>int32 CapDirection = 12;</code>
             */
            public int getCapDirection() {
                return capDirection_;
            }

            /**
             * <code>int32 CapDirection = 12;</code>
             */
            public Builder setCapDirection(int value) {

                capDirection_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 CapDirection = 12;</code>
             */
            public Builder clearCapDirection() {

                capDirection_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string MonitorDirection = 13;</code>
             */
            public String getMonitorDirection() {
                Object ref = monitorDirection_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    monitorDirection_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string MonitorDirection = 13;</code>
             */
            public Builder setMonitorDirection(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                monitorDirection_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string MonitorDirection = 13;</code>
             */
            public com.google.protobuf.ByteString getMonitorDirectionBytes() {
                Object ref = monitorDirection_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    monitorDirection_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string MonitorDirection = 13;</code>
             */
            public Builder setMonitorDirectionBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                monitorDirection_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string MonitorDirection = 13;</code>
             */
            public Builder clearMonitorDirection() {

                monitorDirection_ = getDefaultInstance().getMonitorDirection();
                onChanged();
                return this;
            }

            /**
             * <code>string MonitorAreaDesc = 14;</code>
             */
            public String getMonitorAreaDesc() {
                Object ref = monitorAreaDesc_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    monitorAreaDesc_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string MonitorAreaDesc = 14;</code>
             */
            public Builder setMonitorAreaDesc(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                monitorAreaDesc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string MonitorAreaDesc = 14;</code>
             */
            public com.google.protobuf.ByteString getMonitorAreaDescBytes() {
                Object ref = monitorAreaDesc_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    monitorAreaDesc_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string MonitorAreaDesc = 14;</code>
             */
            public Builder setMonitorAreaDescBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                monitorAreaDesc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string MonitorAreaDesc = 14;</code>
             */
            public Builder clearMonitorAreaDesc() {

                monitorAreaDesc_ = getDefaultInstance().getMonitorAreaDesc();
                onChanged();
                return this;
            }

            /**
             * <code>int32 IsOnline = 15;</code>
             */
            public int getIsOnline() {
                return isOnline_;
            }

            /**
             * <code>int32 IsOnline = 15;</code>
             */
            public Builder setIsOnline(int value) {

                isOnline_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 IsOnline = 15;</code>
             */
            public Builder clearIsOnline() {

                isOnline_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string OwnerApsID = 16;</code>
             */
            public String getOwnerApsID() {
                Object ref = ownerApsID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    ownerApsID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string OwnerApsID = 16;</code>
             */
            public Builder setOwnerApsID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ownerApsID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string OwnerApsID = 16;</code>
             */
            public com.google.protobuf.ByteString getOwnerApsIDBytes() {
                Object ref = ownerApsID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    ownerApsID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string OwnerApsID = 16;</code>
             */
            public Builder setOwnerApsIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ownerApsID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string OwnerApsID = 16;</code>
             */
            public Builder clearOwnerApsID() {

                ownerApsID_ = getDefaultInstance().getOwnerApsID();
                onChanged();
                return this;
            }

            /**
             * <code>string UserId = 17;</code>
             */
            public String getUserId() {
                Object ref = userId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    userId_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string UserId = 17;</code>
             */
            public Builder setUserId(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string UserId = 17;</code>
             */
            public com.google.protobuf.ByteString getUserIdBytes() {
                Object ref = userId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    userId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string UserId = 17;</code>
             */
            public Builder setUserIdBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string UserId = 17;</code>
             */
            public Builder clearUserId() {

                userId_ = getDefaultInstance().getUserId();
                onChanged();
                return this;
            }

            /**
             * <code>string Password = 18;</code>
             */
            public String getPassword() {
                Object ref = password_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    password_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Password = 18;</code>
             */
            public Builder setPassword(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Password = 18;</code>
             */
            public com.google.protobuf.ByteString getPasswordBytes() {
                Object ref = password_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    password_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Password = 18;</code>
             */
            public Builder setPasswordBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Password = 18;</code>
             */
            public Builder clearPassword() {

                password_ = getDefaultInstance().getPassword();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:APE_Proto)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
