// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: lane.proto

package com.kedacom.ctsp.cvf.viid.common.protobuf;

public final class LaneProtobuf {
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Lane_Proto_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Lane_Proto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\nlane.proto\"\242\001\n\nLane_Proto\022\022\n\nTollgateI"
            + "D\030\001 \001(\t\022\016\n\006LaneId\030\002 \001(\005\022\016\n\006LaneNo\030\003 \001(\005\022"
            + "\014\n\004Name\030\004 \001(\t\022\021\n\tDirection\030\005 \001(\005\022\014\n\004Desc"
            + "\030\006 \001(\t\022\020\n\010MaxSpeed\030\007 \001(\001\022\020\n\010CityPass\030\010 \001"
            + "(\005\022\r\n\005APEID\030\t \001(\tB9\n)com.kedacom.ctsp.cv"
            + "f.viid.common.protobufB\014LaneProtobufb\006pr" + "oto3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry
                    assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_Lane_Proto_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Lane_Proto_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Lane_Proto_descriptor, new String[] {"TollgateID", "LaneId", "LaneNo", "Name", "Direction",
                "Desc", "MaxSpeed", "CityPass", "APEID",});
    }

    private LaneProtobuf() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite)registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    public interface Lane_ProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Lane_Proto)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string TollgateID = 1;</code>
         */
        String getTollgateID();

        /**
         * <code>string TollgateID = 1;</code>
         */
        com.google.protobuf.ByteString getTollgateIDBytes();

        /**
         * <code>int32 LaneId = 2;</code>
         */
        int getLaneId();

        /**
         * <code>int32 LaneNo = 3;</code>
         */
        int getLaneNo();

        /**
         * <code>string Name = 4;</code>
         */
        String getName();

        /**
         * <code>string Name = 4;</code>
         */
        com.google.protobuf.ByteString getNameBytes();

        /**
         * <code>int32 Direction = 5;</code>
         */
        int getDirection();

        /**
         * <code>string Desc = 6;</code>
         */
        String getDesc();

        /**
         * <code>string Desc = 6;</code>
         */
        com.google.protobuf.ByteString getDescBytes();

        /**
         * <code>double MaxSpeed = 7;</code>
         */
        double getMaxSpeed();

        /**
         * <code>int32 CityPass = 8;</code>
         */
        int getCityPass();

        /**
         * <code>string APEID = 9;</code>
         */
        String getAPEID();

        /**
         * <code>string APEID = 9;</code>
         */
        com.google.protobuf.ByteString getAPEIDBytes();
    }

    /**
     * Protobuf type {@code Lane_Proto}
     */
    public static final class Lane_Proto extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Lane_Proto)
        Lane_ProtoOrBuilder {
        public static final int TOLLGATEID_FIELD_NUMBER = 1;
        public static final int LANEID_FIELD_NUMBER = 2;
        public static final int LANENO_FIELD_NUMBER = 3;
        public static final int NAME_FIELD_NUMBER = 4;
        public static final int DIRECTION_FIELD_NUMBER = 5;
        public static final int DESC_FIELD_NUMBER = 6;
        public static final int MAXSPEED_FIELD_NUMBER = 7;
        public static final int CITYPASS_FIELD_NUMBER = 8;
        public static final int APEID_FIELD_NUMBER = 9;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Lane_Proto)
        private static final Lane_Proto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Lane_Proto> PARSER =
            new com.google.protobuf.AbstractParser<Lane_Proto>() {
                public Lane_Proto parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Lane_Proto(input, extensionRegistry);
                }
            };

        static {
            DEFAULT_INSTANCE = new Lane_Proto();
        }

        private volatile Object tollgateID_;
        private int laneId_;
        private int laneNo_;
        private volatile Object name_;
        private int direction_;
        private volatile Object desc_;
        private double maxSpeed_;
        private int cityPass_;
        private volatile Object aPEID_;
        private byte memoizedIsInitialized = -1;

        // Use Lane_Proto.newBuilder() to construct.
        private Lane_Proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Lane_Proto() {
            tollgateID_ = "";
            laneId_ = 0;
            laneNo_ = 0;
            name_ = "";
            direction_ = 0;
            desc_ = "";
            maxSpeed_ = 0D;
            cityPass_ = 0;
            aPEID_ = "";
        }

        private Lane_Proto(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            tollgateID_ = s;
                            break;
                        }
                        case 16: {

                            laneId_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            laneNo_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 40: {

                            direction_ = input.readInt32();
                            break;
                        }
                        case 50: {
                            String s = input.readStringRequireUtf8();

                            desc_ = s;
                            break;
                        }
                        case 57: {

                            maxSpeed_ = input.readDouble();
                            break;
                        }
                        case 64: {

                            cityPass_ = input.readInt32();
                            break;
                        }
                        case 74: {
                            String s = input.readStringRequireUtf8();

                            aPEID_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return LaneProtobuf.internal_static_Lane_Proto_descriptor;
        }

        public static Lane_Proto parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Lane_Proto parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Lane_Proto parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Lane_Proto parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Lane_Proto parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Lane_Proto parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Lane_Proto parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Lane_Proto parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Lane_Proto parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static Lane_Proto parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static Lane_Proto parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Lane_Proto parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Lane_Proto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Lane_Proto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Lane_Proto> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return LaneProtobuf.internal_static_Lane_Proto_fieldAccessorTable
                .ensureFieldAccessorsInitialized(Lane_Proto.class, Builder.class);
        }

        /**
         * <code>string TollgateID = 1;</code>
         */
        public String getTollgateID() {
            Object ref = tollgateID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                tollgateID_ = s;
                return s;
            }
        }

        /**
         * <code>string TollgateID = 1;</code>
         */
        public com.google.protobuf.ByteString getTollgateIDBytes() {
            Object ref = tollgateID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                tollgateID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int32 LaneId = 2;</code>
         */
        public int getLaneId() {
            return laneId_;
        }

        /**
         * <code>int32 LaneNo = 3;</code>
         */
        public int getLaneNo() {
            return laneNo_;
        }

        /**
         * <code>string Name = 4;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string Name = 4;</code>
         */
        public com.google.protobuf.ByteString getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int32 Direction = 5;</code>
         */
        public int getDirection() {
            return direction_;
        }

        /**
         * <code>string Desc = 6;</code>
         */
        public String getDesc() {
            Object ref = desc_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                desc_ = s;
                return s;
            }
        }

        /**
         * <code>string Desc = 6;</code>
         */
        public com.google.protobuf.ByteString getDescBytes() {
            Object ref = desc_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                desc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>double MaxSpeed = 7;</code>
         */
        public double getMaxSpeed() {
            return maxSpeed_;
        }

        /**
         * <code>int32 CityPass = 8;</code>
         */
        public int getCityPass() {
            return cityPass_;
        }

        /**
         * <code>string APEID = 9;</code>
         */
        public String getAPEID() {
            Object ref = aPEID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                aPEID_ = s;
                return s;
            }
        }

        /**
         * <code>string APEID = 9;</code>
         */
        public com.google.protobuf.ByteString getAPEIDBytes() {
            Object ref = aPEID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                aPEID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getTollgateIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tollgateID_);
            }
            if (laneId_ != 0) {
                output.writeInt32(2, laneId_);
            }
            if (laneNo_ != 0) {
                output.writeInt32(3, laneNo_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
            }
            if (direction_ != 0) {
                output.writeInt32(5, direction_);
            }
            if (!getDescBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, desc_);
            }
            if (maxSpeed_ != 0D) {
                output.writeDouble(7, maxSpeed_);
            }
            if (cityPass_ != 0) {
                output.writeInt32(8, cityPass_);
            }
            if (!getAPEIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 9, aPEID_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!getTollgateIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tollgateID_);
            }
            if (laneId_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, laneId_);
            }
            if (laneNo_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(3, laneNo_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
            }
            if (direction_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(5, direction_);
            }
            if (!getDescBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, desc_);
            }
            if (maxSpeed_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(7, maxSpeed_);
            }
            if (cityPass_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(8, cityPass_);
            }
            if (!getAPEIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, aPEID_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Lane_Proto)) {
                return super.equals(obj);
            }
            Lane_Proto other = (Lane_Proto)obj;

            boolean result = true;
            result = result && getTollgateID().equals(other.getTollgateID());
            result = result && (getLaneId() == other.getLaneId());
            result = result && (getLaneNo() == other.getLaneNo());
            result = result && getName().equals(other.getName());
            result = result && (getDirection() == other.getDirection());
            result = result && getDesc().equals(other.getDesc());
            result = result && (Double.doubleToLongBits(getMaxSpeed()) == Double.doubleToLongBits(other.getMaxSpeed()));
            result = result && (getCityPass() == other.getCityPass());
            result = result && getAPEID().equals(other.getAPEID());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TOLLGATEID_FIELD_NUMBER;
            hash = (53 * hash) + getTollgateID().hashCode();
            hash = (37 * hash) + LANEID_FIELD_NUMBER;
            hash = (53 * hash) + getLaneId();
            hash = (37 * hash) + LANENO_FIELD_NUMBER;
            hash = (53 * hash) + getLaneNo();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
            hash = (53 * hash) + getDirection();
            hash = (37 * hash) + DESC_FIELD_NUMBER;
            hash = (53 * hash) + getDesc().hashCode();
            hash = (37 * hash) + MAXSPEED_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getMaxSpeed()));
            hash = (37 * hash) + CITYPASS_FIELD_NUMBER;
            hash = (53 * hash) + getCityPass();
            hash = (37 * hash) + APEID_FIELD_NUMBER;
            hash = (53 * hash) + getAPEID().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Lane_Proto> getParserForType() {
            return PARSER;
        }

        public Lane_Proto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Lane_Proto}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Lane_Proto)
            Lane_ProtoOrBuilder {
            private Object tollgateID_ = "";
            private int laneId_;
            private int laneNo_;
            private Object name_ = "";
            private int direction_;
            private Object desc_ = "";
            private double maxSpeed_;
            private int cityPass_;
            private Object aPEID_ = "";

            // Construct using com.kedacom.ctsp.cvf.viid.common.protobuf.LaneProtobuf.Lane_Proto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return LaneProtobuf.internal_static_Lane_Proto_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return LaneProtobuf.internal_static_Lane_Proto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(Lane_Proto.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                tollgateID_ = "";

                laneId_ = 0;

                laneNo_ = 0;

                name_ = "";

                direction_ = 0;

                desc_ = "";

                maxSpeed_ = 0D;

                cityPass_ = 0;

                aPEID_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return LaneProtobuf.internal_static_Lane_Proto_descriptor;
            }

            public Lane_Proto getDefaultInstanceForType() {
                return Lane_Proto.getDefaultInstance();
            }

            public Lane_Proto build() {
                Lane_Proto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Lane_Proto buildPartial() {
                Lane_Proto result = new Lane_Proto(this);
                result.tollgateID_ = tollgateID_;
                result.laneId_ = laneId_;
                result.laneNo_ = laneNo_;
                result.name_ = name_;
                result.direction_ = direction_;
                result.desc_ = desc_;
                result.maxSpeed_ = maxSpeed_;
                result.cityPass_ = cityPass_;
                result.aPEID_ = aPEID_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder)super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder)super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder)super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                Object value) {
                return (Builder)super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Lane_Proto) {
                    return mergeFrom((Lane_Proto)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Lane_Proto other) {
                if (other == Lane_Proto.getDefaultInstance())
                    return this;
                if (!other.getTollgateID().isEmpty()) {
                    tollgateID_ = other.tollgateID_;
                    onChanged();
                }
                if (other.getLaneId() != 0) {
                    setLaneId(other.getLaneId());
                }
                if (other.getLaneNo() != 0) {
                    setLaneNo(other.getLaneNo());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getDirection() != 0) {
                    setDirection(other.getDirection());
                }
                if (!other.getDesc().isEmpty()) {
                    desc_ = other.desc_;
                    onChanged();
                }
                if (other.getMaxSpeed() != 0D) {
                    setMaxSpeed(other.getMaxSpeed());
                }
                if (other.getCityPass() != 0) {
                    setCityPass(other.getCityPass());
                }
                if (!other.getAPEID().isEmpty()) {
                    aPEID_ = other.aPEID_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                Lane_Proto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Lane_Proto)e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public String getTollgateID() {
                Object ref = tollgateID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    tollgateID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public Builder setTollgateID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                tollgateID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public com.google.protobuf.ByteString getTollgateIDBytes() {
                Object ref = tollgateID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    tollgateID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public Builder setTollgateIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                tollgateID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public Builder clearTollgateID() {

                tollgateID_ = getDefaultInstance().getTollgateID();
                onChanged();
                return this;
            }

            /**
             * <code>int32 LaneId = 2;</code>
             */
            public int getLaneId() {
                return laneId_;
            }

            /**
             * <code>int32 LaneId = 2;</code>
             */
            public Builder setLaneId(int value) {

                laneId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 LaneId = 2;</code>
             */
            public Builder clearLaneId() {

                laneId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>int32 LaneNo = 3;</code>
             */
            public int getLaneNo() {
                return laneNo_;
            }

            /**
             * <code>int32 LaneNo = 3;</code>
             */
            public Builder setLaneNo(int value) {

                laneNo_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 LaneNo = 3;</code>
             */
            public Builder clearLaneNo() {

                laneNo_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 4;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Name = 4;</code>
             */
            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 4;</code>
             */
            public com.google.protobuf.ByteString getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Name = 4;</code>
             */
            public Builder setNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 4;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>int32 Direction = 5;</code>
             */
            public int getDirection() {
                return direction_;
            }

            /**
             * <code>int32 Direction = 5;</code>
             */
            public Builder setDirection(int value) {

                direction_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 Direction = 5;</code>
             */
            public Builder clearDirection() {

                direction_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string Desc = 6;</code>
             */
            public String getDesc() {
                Object ref = desc_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    desc_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Desc = 6;</code>
             */
            public Builder setDesc(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                desc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Desc = 6;</code>
             */
            public com.google.protobuf.ByteString getDescBytes() {
                Object ref = desc_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    desc_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Desc = 6;</code>
             */
            public Builder setDescBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                desc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Desc = 6;</code>
             */
            public Builder clearDesc() {

                desc_ = getDefaultInstance().getDesc();
                onChanged();
                return this;
            }

            /**
             * <code>double MaxSpeed = 7;</code>
             */
            public double getMaxSpeed() {
                return maxSpeed_;
            }

            /**
             * <code>double MaxSpeed = 7;</code>
             */
            public Builder setMaxSpeed(double value) {

                maxSpeed_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double MaxSpeed = 7;</code>
             */
            public Builder clearMaxSpeed() {

                maxSpeed_ = 0D;
                onChanged();
                return this;
            }

            /**
             * <code>int32 CityPass = 8;</code>
             */
            public int getCityPass() {
                return cityPass_;
            }

            /**
             * <code>int32 CityPass = 8;</code>
             */
            public Builder setCityPass(int value) {

                cityPass_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 CityPass = 8;</code>
             */
            public Builder clearCityPass() {

                cityPass_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string APEID = 9;</code>
             */
            public String getAPEID() {
                Object ref = aPEID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    aPEID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string APEID = 9;</code>
             */
            public Builder setAPEID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                aPEID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string APEID = 9;</code>
             */
            public com.google.protobuf.ByteString getAPEIDBytes() {
                Object ref = aPEID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    aPEID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string APEID = 9;</code>
             */
            public Builder setAPEIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                aPEID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string APEID = 9;</code>
             */
            public Builder clearAPEID() {

                aPEID_ = getDefaultInstance().getAPEID();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:Lane_Proto)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
