// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: dispositionnotify.proto

package com.kedacom.ctsp.cvf.viid.common.protobuf;

public final class NotificationlistProtobuf {
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_DispositionNotification_Proto_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_DispositionNotification_Proto_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_DispositionNotificationList_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_DispositionNotificationList_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\027dispositionnotify.proto\032\022motorvehicle."
            + "proto\032\014person.proto\"\327\001\n\035DispositionNotif"
            + "ication_Proto\022\026\n\016NotificationID\030\001 \001(\t\022\025\n"
            + "\rDispositionID\030\002 \001(\t\022\r\n\005Title\030\003 \001(\t\022\023\n\013T"
            + "riggerTime\030\004 \001(\003\022\023\n\013CntObjectID\030\005 \001(\t\022\035\n"
            + "\006Person\030\006 \001(\0132\r.Person_Proto\022/\n\022MotorVeh"
            + "icleObject\030\007 \001(\0132\023.MotorVehicle_Proto\"^\n"
            + "\033DispositionNotificationList\022?\n\027Disposit"
            + "ionNotification\030\001 \003(\0132\036.DispositionNotif" + "ication_ProtoBE\n)com.kedacom.ctsp.cvf.vi"
            + "id.common.protobufB\030NotificationlistProt" + "obufb\006proto3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                @Override
                public com.google.protobuf.ExtensionRegistry
                    assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {MotorProtobuf.getDescriptor(),
                com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.getDescriptor(),},
            assigner);
        internal_static_DispositionNotification_Proto_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_DispositionNotification_Proto_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_DispositionNotification_Proto_descriptor, new String[] {"NotificationID",
                    "DispositionID", "Title", "TriggerTime", "CntObjectID", "Person", "MotorVehicleObject",});
        internal_static_DispositionNotificationList_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_DispositionNotificationList_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_DispositionNotificationList_descriptor, new String[] {"DispositionNotification",});
        MotorProtobuf.getDescriptor();
        com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.getDescriptor();
    }

    private NotificationlistProtobuf() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite)registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    public interface DispositionNotification_ProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DispositionNotification_Proto)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string NotificationID = 1;</code>
         */
        String getNotificationID();

        /**
         * <code>string NotificationID = 1;</code>
         */
        com.google.protobuf.ByteString getNotificationIDBytes();

        /**
         * <code>string DispositionID = 2;</code>
         */
        String getDispositionID();

        /**
         * <code>string DispositionID = 2;</code>
         */
        com.google.protobuf.ByteString getDispositionIDBytes();

        /**
         * <code>string Title = 3;</code>
         */
        String getTitle();

        /**
         * <code>string Title = 3;</code>
         */
        com.google.protobuf.ByteString getTitleBytes();

        /**
         * <code>int64 TriggerTime = 4;</code>
         */
        long getTriggerTime();

        /**
         * <code>string CntObjectID = 5;</code>
         */
        String getCntObjectID();

        /**
         * <code>string CntObjectID = 5;</code>
         */
        com.google.protobuf.ByteString getCntObjectIDBytes();

        /**
         * <code>.Person_Proto Person = 6;</code>
         */
        boolean hasPerson();

        /**
         * <code>.Person_Proto Person = 6;</code>
         */
        com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto getPerson();

        /**
         * <code>.Person_Proto Person = 6;</code>
         */
        com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_ProtoOrBuilder getPersonOrBuilder();

        /**
         * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
         */
        boolean hasMotorVehicleObject();

        /**
         * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
         */
        MotorProtobuf.MotorVehicle_Proto getMotorVehicleObject();

        /**
         * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
         */
        MotorProtobuf.MotorVehicle_ProtoOrBuilder getMotorVehicleObjectOrBuilder();
    }

    public interface DispositionNotificationListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DispositionNotificationList)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        java.util.List<DispositionNotification_Proto> getDispositionNotificationList();

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        DispositionNotification_Proto getDispositionNotification(int index);

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        int getDispositionNotificationCount();

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        java.util.List<? extends DispositionNotification_ProtoOrBuilder> getDispositionNotificationOrBuilderList();

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        DispositionNotification_ProtoOrBuilder getDispositionNotificationOrBuilder(int index);
    }

    /**
     * Protobuf type {@code DispositionNotification_Proto}
     */
    public static final class DispositionNotification_Proto extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:DispositionNotification_Proto)
        DispositionNotification_ProtoOrBuilder {
        public static final int NOTIFICATIONID_FIELD_NUMBER = 1;
        public static final int DISPOSITIONID_FIELD_NUMBER = 2;
        public static final int TITLE_FIELD_NUMBER = 3;
        public static final int TRIGGERTIME_FIELD_NUMBER = 4;
        public static final int CNTOBJECTID_FIELD_NUMBER = 5;
        public static final int PERSON_FIELD_NUMBER = 6;
        public static final int MOTORVEHICLEOBJECT_FIELD_NUMBER = 7;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:DispositionNotification_Proto)
        private static final DispositionNotification_Proto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<DispositionNotification_Proto> PARSER =
            new com.google.protobuf.AbstractParser<DispositionNotification_Proto>() {
                @Override
                public DispositionNotification_Proto parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new DispositionNotification_Proto(input, extensionRegistry);
                }
            };

        static {
            DEFAULT_INSTANCE = new DispositionNotification_Proto();
        }

        private volatile Object notificationID_;
        private volatile Object dispositionID_;
        private volatile Object title_;
        private long triggerTime_;
        private volatile Object cntObjectID_;
        private com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto person_;
        private MotorProtobuf.MotorVehicle_Proto motorVehicleObject_;
        private byte memoizedIsInitialized = -1;

        // Use DispositionNotification_Proto.newBuilder() to construct.
        private DispositionNotification_Proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private DispositionNotification_Proto() {
            notificationID_ = "";
            dispositionID_ = "";
            title_ = "";
            triggerTime_ = 0L;
            cntObjectID_ = "";
        }

        private DispositionNotification_Proto(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            notificationID_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            dispositionID_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            title_ = s;
                            break;
                        }
                        case 32: {

                            triggerTime_ = input.readInt64();
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            cntObjectID_ = s;
                            break;
                        }
                        case 50: {
                            com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.Builder subBuilder =
                                null;
                            if (person_ != null) {
                                subBuilder = person_.toBuilder();
                            }
                            person_ = input.readMessage(
                                com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.parser(),
                                extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(person_);
                                person_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 58: {
                            MotorProtobuf.MotorVehicle_Proto.Builder subBuilder = null;
                            if (motorVehicleObject_ != null) {
                                subBuilder = motorVehicleObject_.toBuilder();
                            }
                            motorVehicleObject_ =
                                input.readMessage(MotorProtobuf.MotorVehicle_Proto.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(motorVehicleObject_);
                                motorVehicleObject_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return NotificationlistProtobuf.internal_static_DispositionNotification_Proto_descriptor;
        }

        public static DispositionNotification_Proto parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DispositionNotification_Proto parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DispositionNotification_Proto parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DispositionNotification_Proto parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DispositionNotification_Proto parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DispositionNotification_Proto parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DispositionNotification_Proto parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static DispositionNotification_Proto parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static DispositionNotification_Proto parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static DispositionNotification_Proto parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static DispositionNotification_Proto parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static DispositionNotification_Proto parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DispositionNotification_Proto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static DispositionNotification_Proto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<DispositionNotification_Proto> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return NotificationlistProtobuf.internal_static_DispositionNotification_Proto_fieldAccessorTable
                .ensureFieldAccessorsInitialized(DispositionNotification_Proto.class, Builder.class);
        }

        /**
         * <code>string NotificationID = 1;</code>
         */
        @Override
        public String getNotificationID() {
            Object ref = notificationID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                notificationID_ = s;
                return s;
            }
        }

        /**
         * <code>string NotificationID = 1;</code>
         */
        @Override
        public com.google.protobuf.ByteString getNotificationIDBytes() {
            Object ref = notificationID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                notificationID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string DispositionID = 2;</code>
         */
        @Override
        public String getDispositionID() {
            Object ref = dispositionID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                dispositionID_ = s;
                return s;
            }
        }

        /**
         * <code>string DispositionID = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString getDispositionIDBytes() {
            Object ref = dispositionID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                dispositionID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Title = 3;</code>
         */
        @Override
        public String getTitle() {
            Object ref = title_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                title_ = s;
                return s;
            }
        }

        /**
         * <code>string Title = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString getTitleBytes() {
            Object ref = title_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                title_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int64 TriggerTime = 4;</code>
         */
        @Override
        public long getTriggerTime() {
            return triggerTime_;
        }

        /**
         * <code>string CntObjectID = 5;</code>
         */
        @Override
        public String getCntObjectID() {
            Object ref = cntObjectID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                cntObjectID_ = s;
                return s;
            }
        }

        /**
         * <code>string CntObjectID = 5;</code>
         */
        @Override
        public com.google.protobuf.ByteString getCntObjectIDBytes() {
            Object ref = cntObjectID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                cntObjectID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>.Person_Proto Person = 6;</code>
         */
        @Override
        public boolean hasPerson() {
            return person_ != null;
        }

        /**
         * <code>.Person_Proto Person = 6;</code>
         */
        @Override
        public com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto getPerson() {
            return person_ == null
                ? com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.getDefaultInstance() : person_;
        }

        /**
         * <code>.Person_Proto Person = 6;</code>
         */
        @Override
        public com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_ProtoOrBuilder getPersonOrBuilder() {
            return getPerson();
        }

        /**
         * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
         */
        @Override
        public boolean hasMotorVehicleObject() {
            return motorVehicleObject_ != null;
        }

        /**
         * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
         */
        @Override
        public MotorProtobuf.MotorVehicle_Proto getMotorVehicleObject() {
            return motorVehicleObject_ == null ? MotorProtobuf.MotorVehicle_Proto.getDefaultInstance()
                : motorVehicleObject_;
        }

        /**
         * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
         */
        @Override
        public MotorProtobuf.MotorVehicle_ProtoOrBuilder getMotorVehicleObjectOrBuilder() {
            return getMotorVehicleObject();
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getNotificationIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, notificationID_);
            }
            if (!getDispositionIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dispositionID_);
            }
            if (!getTitleBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
            }
            if (triggerTime_ != 0L) {
                output.writeInt64(4, triggerTime_);
            }
            if (!getCntObjectIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cntObjectID_);
            }
            if (person_ != null) {
                output.writeMessage(6, getPerson());
            }
            if (motorVehicleObject_ != null) {
                output.writeMessage(7, getMotorVehicleObject());
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!getNotificationIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, notificationID_);
            }
            if (!getDispositionIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dispositionID_);
            }
            if (!getTitleBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
            }
            if (triggerTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, triggerTime_);
            }
            if (!getCntObjectIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cntObjectID_);
            }
            if (person_ != null) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(6, getPerson());
            }
            if (motorVehicleObject_ != null) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, getMotorVehicleObject());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof DispositionNotification_Proto)) {
                return super.equals(obj);
            }
            DispositionNotification_Proto other = (DispositionNotification_Proto)obj;

            boolean result = true;
            result = result && getNotificationID().equals(other.getNotificationID());
            result = result && getDispositionID().equals(other.getDispositionID());
            result = result && getTitle().equals(other.getTitle());
            result = result && (getTriggerTime() == other.getTriggerTime());
            result = result && getCntObjectID().equals(other.getCntObjectID());
            result = result && (hasPerson() == other.hasPerson());
            if (hasPerson()) {
                result = result && getPerson().equals(other.getPerson());
            }
            result = result && (hasMotorVehicleObject() == other.hasMotorVehicleObject());
            if (hasMotorVehicleObject()) {
                result = result && getMotorVehicleObject().equals(other.getMotorVehicleObject());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NOTIFICATIONID_FIELD_NUMBER;
            hash = (53 * hash) + getNotificationID().hashCode();
            hash = (37 * hash) + DISPOSITIONID_FIELD_NUMBER;
            hash = (53 * hash) + getDispositionID().hashCode();
            hash = (37 * hash) + TITLE_FIELD_NUMBER;
            hash = (53 * hash) + getTitle().hashCode();
            hash = (37 * hash) + TRIGGERTIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTriggerTime());
            hash = (37 * hash) + CNTOBJECTID_FIELD_NUMBER;
            hash = (53 * hash) + getCntObjectID().hashCode();
            if (hasPerson()) {
                hash = (37 * hash) + PERSON_FIELD_NUMBER;
                hash = (53 * hash) + getPerson().hashCode();
            }
            if (hasMotorVehicleObject()) {
                hash = (37 * hash) + MOTORVEHICLEOBJECT_FIELD_NUMBER;
                hash = (53 * hash) + getMotorVehicleObject().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<DispositionNotification_Proto> getParserForType() {
            return PARSER;
        }

        @Override
        public DispositionNotification_Proto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code DispositionNotification_Proto}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:DispositionNotification_Proto)
            DispositionNotification_ProtoOrBuilder {
            private Object notificationID_ = "";
            private Object dispositionID_ = "";
            private Object title_ = "";
            private long triggerTime_;
            private Object cntObjectID_ = "";
            private com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto person_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto,
                com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.Builder,
                com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_ProtoOrBuilder> personBuilder_;
            private MotorProtobuf.MotorVehicle_Proto motorVehicleObject_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<MotorProtobuf.MotorVehicle_Proto,
                MotorProtobuf.MotorVehicle_Proto.Builder,
                MotorProtobuf.MotorVehicle_ProtoOrBuilder> motorVehicleObjectBuilder_;

            // Construct using
            // com.kedacom.ctsp.cvf.viid.common.protobuf.NotificationlistProtobuf.DispositionNotification_Proto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return NotificationlistProtobuf.internal_static_DispositionNotification_Proto_descriptor;
            }

            @Override
            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return NotificationlistProtobuf.internal_static_DispositionNotification_Proto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(DispositionNotification_Proto.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                notificationID_ = "";

                dispositionID_ = "";

                title_ = "";

                triggerTime_ = 0L;

                cntObjectID_ = "";

                if (personBuilder_ == null) {
                    person_ = null;
                } else {
                    person_ = null;
                    personBuilder_ = null;
                }
                if (motorVehicleObjectBuilder_ == null) {
                    motorVehicleObject_ = null;
                } else {
                    motorVehicleObject_ = null;
                    motorVehicleObjectBuilder_ = null;
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return NotificationlistProtobuf.internal_static_DispositionNotification_Proto_descriptor;
            }

            @Override
            public DispositionNotification_Proto getDefaultInstanceForType() {
                return DispositionNotification_Proto.getDefaultInstance();
            }

            @Override
            public DispositionNotification_Proto build() {
                DispositionNotification_Proto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public DispositionNotification_Proto buildPartial() {
                DispositionNotification_Proto result = new DispositionNotification_Proto(this);
                result.notificationID_ = notificationID_;
                result.dispositionID_ = dispositionID_;
                result.title_ = title_;
                result.triggerTime_ = triggerTime_;
                result.cntObjectID_ = cntObjectID_;
                if (personBuilder_ == null) {
                    result.person_ = person_;
                } else {
                    result.person_ = personBuilder_.build();
                }
                if (motorVehicleObjectBuilder_ == null) {
                    result.motorVehicleObject_ = motorVehicleObject_;
                } else {
                    result.motorVehicleObject_ = motorVehicleObjectBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder)super.clone();
            }

            @Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.setField(field, value);
            }

            @Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder)super.clearField(field);
            }

            @Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder)super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            Object value) {
                return (Builder)super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DispositionNotification_Proto) {
                    return mergeFrom((DispositionNotification_Proto)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DispositionNotification_Proto other) {
                if (other == DispositionNotification_Proto.getDefaultInstance()) {
                    return this;
                }
                if (!other.getNotificationID().isEmpty()) {
                    notificationID_ = other.notificationID_;
                    onChanged();
                }
                if (!other.getDispositionID().isEmpty()) {
                    dispositionID_ = other.dispositionID_;
                    onChanged();
                }
                if (!other.getTitle().isEmpty()) {
                    title_ = other.title_;
                    onChanged();
                }
                if (other.getTriggerTime() != 0L) {
                    setTriggerTime(other.getTriggerTime());
                }
                if (!other.getCntObjectID().isEmpty()) {
                    cntObjectID_ = other.cntObjectID_;
                    onChanged();
                }
                if (other.hasPerson()) {
                    mergePerson(other.getPerson());
                }
                if (other.hasMotorVehicleObject()) {
                    mergeMotorVehicleObject(other.getMotorVehicleObject());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                DispositionNotification_Proto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (DispositionNotification_Proto)e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string NotificationID = 1;</code>
             */
            @Override
            public String getNotificationID() {
                Object ref = notificationID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    notificationID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string NotificationID = 1;</code>
             */
            public Builder setNotificationID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                notificationID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string NotificationID = 1;</code>
             */
            @Override
            public com.google.protobuf.ByteString getNotificationIDBytes() {
                Object ref = notificationID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    notificationID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string NotificationID = 1;</code>
             */
            public Builder setNotificationIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                notificationID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string NotificationID = 1;</code>
             */
            public Builder clearNotificationID() {

                notificationID_ = getDefaultInstance().getNotificationID();
                onChanged();
                return this;
            }

            /**
             * <code>string DispositionID = 2;</code>
             */
            @Override
            public String getDispositionID() {
                Object ref = dispositionID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    dispositionID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string DispositionID = 2;</code>
             */
            public Builder setDispositionID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                dispositionID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string DispositionID = 2;</code>
             */
            @Override
            public com.google.protobuf.ByteString getDispositionIDBytes() {
                Object ref = dispositionID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    dispositionID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string DispositionID = 2;</code>
             */
            public Builder setDispositionIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                dispositionID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string DispositionID = 2;</code>
             */
            public Builder clearDispositionID() {

                dispositionID_ = getDefaultInstance().getDispositionID();
                onChanged();
                return this;
            }

            /**
             * <code>string Title = 3;</code>
             */
            @Override
            public String getTitle() {
                Object ref = title_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    title_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Title = 3;</code>
             */
            public Builder setTitle(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                title_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Title = 3;</code>
             */
            @Override
            public com.google.protobuf.ByteString getTitleBytes() {
                Object ref = title_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    title_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Title = 3;</code>
             */
            public Builder setTitleBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                title_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Title = 3;</code>
             */
            public Builder clearTitle() {

                title_ = getDefaultInstance().getTitle();
                onChanged();
                return this;
            }

            /**
             * <code>int64 TriggerTime = 4;</code>
             */
            @Override
            public long getTriggerTime() {
                return triggerTime_;
            }

            /**
             * <code>int64 TriggerTime = 4;</code>
             */
            public Builder setTriggerTime(long value) {

                triggerTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 TriggerTime = 4;</code>
             */
            public Builder clearTriggerTime() {

                triggerTime_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>string CntObjectID = 5;</code>
             */
            @Override
            public String getCntObjectID() {
                Object ref = cntObjectID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    cntObjectID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string CntObjectID = 5;</code>
             */
            public Builder setCntObjectID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                cntObjectID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string CntObjectID = 5;</code>
             */
            @Override
            public com.google.protobuf.ByteString getCntObjectIDBytes() {
                Object ref = cntObjectID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    cntObjectID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string CntObjectID = 5;</code>
             */
            public Builder setCntObjectIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                cntObjectID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string CntObjectID = 5;</code>
             */
            public Builder clearCntObjectID() {

                cntObjectID_ = getDefaultInstance().getCntObjectID();
                onChanged();
                return this;
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            @Override
            public boolean hasPerson() {
                return personBuilder_ != null || person_ != null;
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            @Override
            public com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto getPerson() {
                if (personBuilder_ == null) {
                    return person_ == null
                        ? com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.getDefaultInstance()
                        : person_;
                } else {
                    return personBuilder_.getMessage();
                }
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            public Builder setPerson(
                com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.Builder builderForValue) {
                if (personBuilder_ == null) {
                    person_ = builderForValue.build();
                    onChanged();
                } else {
                    personBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            public Builder setPerson(com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto value) {
                if (personBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    person_ = value;
                    onChanged();
                } else {
                    personBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            public Builder mergePerson(com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto value) {
                if (personBuilder_ == null) {
                    if (person_ != null) {
                        person_ = com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto
                            .newBuilder(person_).mergeFrom(value).buildPartial();
                    } else {
                        person_ = value;
                    }
                    onChanged();
                } else {
                    personBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            public Builder clearPerson() {
                if (personBuilder_ == null) {
                    person_ = null;
                    onChanged();
                } else {
                    person_ = null;
                    personBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            public com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.Builder getPersonBuilder() {

                onChanged();
                return getPersonFieldBuilder().getBuilder();
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            @Override
            public com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_ProtoOrBuilder getPersonOrBuilder() {
                if (personBuilder_ != null) {
                    return personBuilder_.getMessageOrBuilder();
                } else {
                    return person_ == null
                        ? com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.getDefaultInstance()
                        : person_;
                }
            }

            /**
             * <code>.Person_Proto Person = 6;</code>
             */
            private
                com.google.protobuf.SingleFieldBuilderV3<
                    com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto,
                    com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.Builder,
                    com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_ProtoOrBuilder>
                getPersonFieldBuilder() {
                if (personBuilder_ == null) {
                    personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto,
                        com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_Proto.Builder,
                        com.kedacom.ctsp.cvf.viid.common.protobuf.PersonProtobuf.Person_ProtoOrBuilder>(getPerson(),
                            getParentForChildren(), isClean());
                    person_ = null;
                }
                return personBuilder_;
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            @Override
            public boolean hasMotorVehicleObject() {
                return motorVehicleObjectBuilder_ != null || motorVehicleObject_ != null;
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            @Override
            public MotorProtobuf.MotorVehicle_Proto getMotorVehicleObject() {
                if (motorVehicleObjectBuilder_ == null) {
                    return motorVehicleObject_ == null ? MotorProtobuf.MotorVehicle_Proto.getDefaultInstance()
                        : motorVehicleObject_;
                } else {
                    return motorVehicleObjectBuilder_.getMessage();
                }
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            public Builder setMotorVehicleObject(MotorProtobuf.MotorVehicle_Proto.Builder builderForValue) {
                if (motorVehicleObjectBuilder_ == null) {
                    motorVehicleObject_ = builderForValue.build();
                    onChanged();
                } else {
                    motorVehicleObjectBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            public Builder setMotorVehicleObject(MotorProtobuf.MotorVehicle_Proto value) {
                if (motorVehicleObjectBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    motorVehicleObject_ = value;
                    onChanged();
                } else {
                    motorVehicleObjectBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            public Builder mergeMotorVehicleObject(MotorProtobuf.MotorVehicle_Proto value) {
                if (motorVehicleObjectBuilder_ == null) {
                    if (motorVehicleObject_ != null) {
                        motorVehicleObject_ = MotorProtobuf.MotorVehicle_Proto.newBuilder(motorVehicleObject_)
                            .mergeFrom(value).buildPartial();
                    } else {
                        motorVehicleObject_ = value;
                    }
                    onChanged();
                } else {
                    motorVehicleObjectBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            public Builder clearMotorVehicleObject() {
                if (motorVehicleObjectBuilder_ == null) {
                    motorVehicleObject_ = null;
                    onChanged();
                } else {
                    motorVehicleObject_ = null;
                    motorVehicleObjectBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            public MotorProtobuf.MotorVehicle_Proto.Builder getMotorVehicleObjectBuilder() {

                onChanged();
                return getMotorVehicleObjectFieldBuilder().getBuilder();
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            @Override
            public MotorProtobuf.MotorVehicle_ProtoOrBuilder getMotorVehicleObjectOrBuilder() {
                if (motorVehicleObjectBuilder_ != null) {
                    return motorVehicleObjectBuilder_.getMessageOrBuilder();
                } else {
                    return motorVehicleObject_ == null ? MotorProtobuf.MotorVehicle_Proto.getDefaultInstance()
                        : motorVehicleObject_;
                }
            }

            /**
             * <code>.MotorVehicle_Proto MotorVehicleObject = 7;</code>
             */
            private
                com.google.protobuf.SingleFieldBuilderV3<MotorProtobuf.MotorVehicle_Proto,
                    MotorProtobuf.MotorVehicle_Proto.Builder, MotorProtobuf.MotorVehicle_ProtoOrBuilder>
                getMotorVehicleObjectFieldBuilder() {
                if (motorVehicleObjectBuilder_ == null) {
                    motorVehicleObjectBuilder_ =
                        new com.google.protobuf.SingleFieldBuilderV3<MotorProtobuf.MotorVehicle_Proto,
                            MotorProtobuf.MotorVehicle_Proto.Builder, MotorProtobuf.MotorVehicle_ProtoOrBuilder>(
                                getMotorVehicleObject(), getParentForChildren(), isClean());
                    motorVehicleObject_ = null;
                }
                return motorVehicleObjectBuilder_;
            }

            @Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:DispositionNotification_Proto)
        }

    }

    /**
     * Protobuf type {@code DispositionNotificationList}
     */
    public static final class DispositionNotificationList extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:DispositionNotificationList)
        DispositionNotificationListOrBuilder {
        public static final int DISPOSITIONNOTIFICATION_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:DispositionNotificationList)
        private static final DispositionNotificationList DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<DispositionNotificationList> PARSER =
            new com.google.protobuf.AbstractParser<DispositionNotificationList>() {
                @Override
                public DispositionNotificationList parsePartialFrom(com.google.protobuf.CodedInputStream input,
                                                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new DispositionNotificationList(input, extensionRegistry);
                }
            };

        static {
            DEFAULT_INSTANCE = new DispositionNotificationList();
        }

        private java.util.List<DispositionNotification_Proto> dispositionNotification_;
        private byte memoizedIsInitialized = -1;

        // Use DispositionNotificationList.newBuilder() to construct.
        private DispositionNotificationList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private DispositionNotificationList() {
            dispositionNotification_ = java.util.Collections.emptyList();
        }

        private DispositionNotificationList(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                dispositionNotification_ = new java.util.ArrayList<DispositionNotification_Proto>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            dispositionNotification_
                                .add(input.readMessage(DispositionNotification_Proto.parser(), extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    dispositionNotification_ = java.util.Collections.unmodifiableList(dispositionNotification_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return NotificationlistProtobuf.internal_static_DispositionNotificationList_descriptor;
        }

        public static DispositionNotificationList parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DispositionNotificationList parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DispositionNotificationList parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DispositionNotificationList parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DispositionNotificationList parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static DispositionNotificationList parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static DispositionNotificationList parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static DispositionNotificationList parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static DispositionNotificationList parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static DispositionNotificationList parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static DispositionNotificationList parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static DispositionNotificationList parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(DispositionNotificationList prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static DispositionNotificationList getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<DispositionNotificationList> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return NotificationlistProtobuf.internal_static_DispositionNotificationList_fieldAccessorTable
                .ensureFieldAccessorsInitialized(DispositionNotificationList.class, Builder.class);
        }

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        @Override
        public java.util.List<DispositionNotification_Proto> getDispositionNotificationList() {
            return dispositionNotification_;
        }

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        @Override
        public java.util.List<? extends DispositionNotification_ProtoOrBuilder>
            getDispositionNotificationOrBuilderList() {
            return dispositionNotification_;
        }

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        @Override
        public int getDispositionNotificationCount() {
            return dispositionNotification_.size();
        }

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        @Override
        public DispositionNotification_Proto getDispositionNotification(int index) {
            return dispositionNotification_.get(index);
        }

        /**
         * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
         */
        @Override
        public DispositionNotification_ProtoOrBuilder getDispositionNotificationOrBuilder(int index) {
            return dispositionNotification_.get(index);
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            for (int i = 0; i < dispositionNotification_.size(); i++) {
                output.writeMessage(1, dispositionNotification_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            for (int i = 0; i < dispositionNotification_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, dispositionNotification_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof DispositionNotificationList)) {
                return super.equals(obj);
            }
            DispositionNotificationList other = (DispositionNotificationList)obj;

            boolean result = true;
            result = result && getDispositionNotificationList().equals(other.getDispositionNotificationList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getDispositionNotificationCount() > 0) {
                hash = (37 * hash) + DISPOSITIONNOTIFICATION_FIELD_NUMBER;
                hash = (53 * hash) + getDispositionNotificationList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<DispositionNotificationList> getParserForType() {
            return PARSER;
        }

        @Override
        public DispositionNotificationList getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code DispositionNotificationList}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:DispositionNotificationList)
            DispositionNotificationListOrBuilder {
            private int bitField0_;
            private java.util.List<DispositionNotification_Proto> dispositionNotification_ =
                java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilderV3<DispositionNotification_Proto,
                DispositionNotification_Proto.Builder,
                DispositionNotification_ProtoOrBuilder> dispositionNotificationBuilder_;

            // Construct using
            // com.kedacom.ctsp.cvf.viid.common.protobuf.NotificationlistProtobuf.DispositionNotificationList.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return NotificationlistProtobuf.internal_static_DispositionNotificationList_descriptor;
            }

            @Override
            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return NotificationlistProtobuf.internal_static_DispositionNotificationList_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(DispositionNotificationList.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                    getDispositionNotificationFieldBuilder();
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                if (dispositionNotificationBuilder_ == null) {
                    dispositionNotification_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    dispositionNotificationBuilder_.clear();
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return NotificationlistProtobuf.internal_static_DispositionNotificationList_descriptor;
            }

            @Override
            public DispositionNotificationList getDefaultInstanceForType() {
                return DispositionNotificationList.getDefaultInstance();
            }

            @Override
            public DispositionNotificationList build() {
                DispositionNotificationList result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public DispositionNotificationList buildPartial() {
                DispositionNotificationList result = new DispositionNotificationList(this);
                int from_bitField0_ = bitField0_;
                if (dispositionNotificationBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        dispositionNotification_ = java.util.Collections.unmodifiableList(dispositionNotification_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.dispositionNotification_ = dispositionNotification_;
                } else {
                    result.dispositionNotification_ = dispositionNotificationBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder)super.clone();
            }

            @Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.setField(field, value);
            }

            @Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder)super.clearField(field);
            }

            @Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder)super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                                            Object value) {
                return (Builder)super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof DispositionNotificationList) {
                    return mergeFrom((DispositionNotificationList)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(DispositionNotificationList other) {
                if (other == DispositionNotificationList.getDefaultInstance()) {
                    return this;
                }
                if (dispositionNotificationBuilder_ == null) {
                    if (!other.dispositionNotification_.isEmpty()) {
                        if (dispositionNotification_.isEmpty()) {
                            dispositionNotification_ = other.dispositionNotification_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureDispositionNotificationIsMutable();
                            dispositionNotification_.addAll(other.dispositionNotification_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.dispositionNotification_.isEmpty()) {
                        if (dispositionNotificationBuilder_.isEmpty()) {
                            dispositionNotificationBuilder_.dispose();
                            dispositionNotificationBuilder_ = null;
                            dispositionNotification_ = other.dispositionNotification_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            dispositionNotificationBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                                    ? getDispositionNotificationFieldBuilder() : null;
                        } else {
                            dispositionNotificationBuilder_.addAllMessages(other.dispositionNotification_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                                     com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                DispositionNotificationList parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (DispositionNotificationList)e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureDispositionNotificationIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    dispositionNotification_ =
                        new java.util.ArrayList<DispositionNotification_Proto>(dispositionNotification_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            @Override
            public java.util.List<DispositionNotification_Proto> getDispositionNotificationList() {
                if (dispositionNotificationBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(dispositionNotification_);
                } else {
                    return dispositionNotificationBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            @Override
            public int getDispositionNotificationCount() {
                if (dispositionNotificationBuilder_ == null) {
                    return dispositionNotification_.size();
                } else {
                    return dispositionNotificationBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            @Override
            public DispositionNotification_Proto getDispositionNotification(int index) {
                if (dispositionNotificationBuilder_ == null) {
                    return dispositionNotification_.get(index);
                } else {
                    return dispositionNotificationBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder setDispositionNotification(int index, DispositionNotification_Proto value) {
                if (dispositionNotificationBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDispositionNotificationIsMutable();
                    dispositionNotification_.set(index, value);
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder setDispositionNotification(int index,
                DispositionNotification_Proto.Builder builderForValue) {
                if (dispositionNotificationBuilder_ == null) {
                    ensureDispositionNotificationIsMutable();
                    dispositionNotification_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder addDispositionNotification(DispositionNotification_Proto value) {
                if (dispositionNotificationBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDispositionNotificationIsMutable();
                    dispositionNotification_.add(value);
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder addDispositionNotification(int index, DispositionNotification_Proto value) {
                if (dispositionNotificationBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureDispositionNotificationIsMutable();
                    dispositionNotification_.add(index, value);
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder addDispositionNotification(DispositionNotification_Proto.Builder builderForValue) {
                if (dispositionNotificationBuilder_ == null) {
                    ensureDispositionNotificationIsMutable();
                    dispositionNotification_.add(builderForValue.build());
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder addDispositionNotification(int index,
                DispositionNotification_Proto.Builder builderForValue) {
                if (dispositionNotificationBuilder_ == null) {
                    ensureDispositionNotificationIsMutable();
                    dispositionNotification_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder addAllDispositionNotification(Iterable<? extends DispositionNotification_Proto> values) {
                if (dispositionNotificationBuilder_ == null) {
                    ensureDispositionNotificationIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(values, dispositionNotification_);
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder clearDispositionNotification() {
                if (dispositionNotificationBuilder_ == null) {
                    dispositionNotification_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public Builder removeDispositionNotification(int index) {
                if (dispositionNotificationBuilder_ == null) {
                    ensureDispositionNotificationIsMutable();
                    dispositionNotification_.remove(index);
                    onChanged();
                } else {
                    dispositionNotificationBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public DispositionNotification_Proto.Builder getDispositionNotificationBuilder(int index) {
                return getDispositionNotificationFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            @Override
            public DispositionNotification_ProtoOrBuilder getDispositionNotificationOrBuilder(int index) {
                if (dispositionNotificationBuilder_ == null) {
                    return dispositionNotification_.get(index);
                } else {
                    return dispositionNotificationBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            @Override
            public java.util.List<? extends DispositionNotification_ProtoOrBuilder>
                getDispositionNotificationOrBuilderList() {
                if (dispositionNotificationBuilder_ != null) {
                    return dispositionNotificationBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(dispositionNotification_);
                }
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public DispositionNotification_Proto.Builder addDispositionNotificationBuilder() {
                return getDispositionNotificationFieldBuilder()
                    .addBuilder(DispositionNotification_Proto.getDefaultInstance());
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public DispositionNotification_Proto.Builder addDispositionNotificationBuilder(int index) {
                return getDispositionNotificationFieldBuilder().addBuilder(index,
                    DispositionNotification_Proto.getDefaultInstance());
            }

            /**
             * <code>repeated .DispositionNotification_Proto DispositionNotification = 1;</code>
             */
            public java.util.List<DispositionNotification_Proto.Builder> getDispositionNotificationBuilderList() {
                return getDispositionNotificationFieldBuilder().getBuilderList();
            }

            private
                com.google.protobuf.RepeatedFieldBuilderV3<DispositionNotification_Proto,
                    DispositionNotification_Proto.Builder, DispositionNotification_ProtoOrBuilder>
                getDispositionNotificationFieldBuilder() {
                if (dispositionNotificationBuilder_ == null) {
                    dispositionNotificationBuilder_ =
                        new com.google.protobuf.RepeatedFieldBuilderV3<DispositionNotification_Proto,
                            DispositionNotification_Proto.Builder, DispositionNotification_ProtoOrBuilder>(
                                dispositionNotification_, ((bitField0_ & 0x00000001) == 0x00000001),
                                getParentForChildren(), isClean());
                    dispositionNotification_ = null;
                }
                return dispositionNotificationBuilder_;
            }

            @Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:DispositionNotificationList)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
