// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: tollgate.proto

package com.kedacom.ctsp.cvf.viid.common.protobuf;

public final class TollgateProtobuf {
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Tollgate_Proto_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_Tollgate_Proto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        String[] descriptorData = {"\n\016tollgate.proto\"\352\001\n\016Tollgate_Proto\022\022\n\nT"
            + "ollgateID\030\001 \001(\t\022\014\n\004Name\030\002 \001(\t\022\021\n\tLongitu"
            + "de\030\003 \001(\001\022\020\n\010Latitude\030\004 \001(\001\022\021\n\tPlaceCode\030"
            + "\005 \001(\t\022\r\n\005Place\030\006 \001(\t\022\016\n\006Status\030\007 \001(\t\022\023\n\013"
            + "TollgateCat\030\010 \001(\t\022\024\n\014TollgateCat2\030\t \001(\005\022"
            + "\017\n\007LaneNum\030\n \001(\005\022\017\n\007OrgCode\030\013 \001(\t\022\022\n\nAct"
            + "iveTime\030\014 \001(\003B=\n)com.kedacom.ctsp.cvf.vi" + "id.common.protobufB\020TollgateProtobufb\006pr"
            + "oto3"};
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry
                    assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
        internal_static_Tollgate_Proto_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Tollgate_Proto_fieldAccessorTable =
            new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_Tollgate_Proto_descriptor,
                new String[] {"TollgateID", "Name", "Longitude", "Latitude", "PlaceCode", "Place", "Status",
                    "TollgateCat", "TollgateCat2", "LaneNum", "OrgCode", "ActiveTime",});
    }

    private TollgateProtobuf() {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite)registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    public interface Tollgate_ProtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Tollgate_Proto)
        com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string TollgateID = 1;</code>
         */
        String getTollgateID();

        /**
         * <code>string TollgateID = 1;</code>
         */
        com.google.protobuf.ByteString getTollgateIDBytes();

        /**
         * <code>string Name = 2;</code>
         */
        String getName();

        /**
         * <code>string Name = 2;</code>
         */
        com.google.protobuf.ByteString getNameBytes();

        /**
         * <code>double Longitude = 3;</code>
         */
        double getLongitude();

        /**
         * <code>double Latitude = 4;</code>
         */
        double getLatitude();

        /**
         * <code>string PlaceCode = 5;</code>
         */
        String getPlaceCode();

        /**
         * <code>string PlaceCode = 5;</code>
         */
        com.google.protobuf.ByteString getPlaceCodeBytes();

        /**
         * <code>string Place = 6;</code>
         */
        String getPlace();

        /**
         * <code>string Place = 6;</code>
         */
        com.google.protobuf.ByteString getPlaceBytes();

        /**
         * <code>string Status = 7;</code>
         */
        String getStatus();

        /**
         * <code>string Status = 7;</code>
         */
        com.google.protobuf.ByteString getStatusBytes();

        /**
         * <code>string TollgateCat = 8;</code>
         */
        String getTollgateCat();

        /**
         * <code>string TollgateCat = 8;</code>
         */
        com.google.protobuf.ByteString getTollgateCatBytes();

        /**
         * <code>int32 TollgateCat2 = 9;</code>
         */
        int getTollgateCat2();

        /**
         * <code>int32 LaneNum = 10;</code>
         */
        int getLaneNum();

        /**
         * <code>string OrgCode = 11;</code>
         */
        String getOrgCode();

        /**
         * <code>string OrgCode = 11;</code>
         */
        com.google.protobuf.ByteString getOrgCodeBytes();

        /**
         * <code>int64 ActiveTime = 12;</code>
         */
        long getActiveTime();
    }

    /**
     * Protobuf type {@code Tollgate_Proto}
     */
    public static final class Tollgate_Proto extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Tollgate_Proto)
        Tollgate_ProtoOrBuilder {
        public static final int TOLLGATEID_FIELD_NUMBER = 1;
        public static final int NAME_FIELD_NUMBER = 2;
        public static final int LONGITUDE_FIELD_NUMBER = 3;
        public static final int LATITUDE_FIELD_NUMBER = 4;
        public static final int PLACECODE_FIELD_NUMBER = 5;
        public static final int PLACE_FIELD_NUMBER = 6;
        public static final int STATUS_FIELD_NUMBER = 7;
        public static final int TOLLGATECAT_FIELD_NUMBER = 8;
        public static final int TOLLGATECAT2_FIELD_NUMBER = 9;
        public static final int LANENUM_FIELD_NUMBER = 10;
        public static final int ORGCODE_FIELD_NUMBER = 11;
        public static final int ACTIVETIME_FIELD_NUMBER = 12;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:Tollgate_Proto)
        private static final Tollgate_Proto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Tollgate_Proto> PARSER =
            new com.google.protobuf.AbstractParser<Tollgate_Proto>() {
                public Tollgate_Proto parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                    return new Tollgate_Proto(input, extensionRegistry);
                }
            };

        static {
            DEFAULT_INSTANCE = new Tollgate_Proto();
        }

        private volatile Object tollgateID_;
        private volatile Object name_;
        private double longitude_;
        private double latitude_;
        private volatile Object placeCode_;
        private volatile Object place_;
        private volatile Object status_;
        private volatile Object tollgateCat_;
        private int tollgateCat2_;
        private int laneNum_;
        private volatile Object orgCode_;
        private long activeTime_;
        private byte memoizedIsInitialized = -1;

        // Use Tollgate_Proto.newBuilder() to construct.
        private Tollgate_Proto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Tollgate_Proto() {
            tollgateID_ = "";
            name_ = "";
            longitude_ = 0D;
            latitude_ = 0D;
            placeCode_ = "";
            place_ = "";
            status_ = "";
            tollgateCat_ = "";
            tollgateCat2_ = 0;
            laneNum_ = 0;
            orgCode_ = "";
            activeTime_ = 0L;
        }

        private Tollgate_Proto(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            tollgateID_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 25: {

                            longitude_ = input.readDouble();
                            break;
                        }
                        case 33: {

                            latitude_ = input.readDouble();
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();

                            placeCode_ = s;
                            break;
                        }
                        case 50: {
                            String s = input.readStringRequireUtf8();

                            place_ = s;
                            break;
                        }
                        case 58: {
                            String s = input.readStringRequireUtf8();

                            status_ = s;
                            break;
                        }
                        case 66: {
                            String s = input.readStringRequireUtf8();

                            tollgateCat_ = s;
                            break;
                        }
                        case 72: {

                            tollgateCat2_ = input.readInt32();
                            break;
                        }
                        case 80: {

                            laneNum_ = input.readInt32();
                            break;
                        }
                        case 90: {
                            String s = input.readStringRequireUtf8();

                            orgCode_ = s;
                            break;
                        }
                        case 96: {

                            activeTime_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return TollgateProtobuf.internal_static_Tollgate_Proto_descriptor;
        }

        public static Tollgate_Proto parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Tollgate_Proto parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Tollgate_Proto parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Tollgate_Proto parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Tollgate_Proto parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Tollgate_Proto parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Tollgate_Proto parseFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Tollgate_Proto parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Tollgate_Proto parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static Tollgate_Proto parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                extensionRegistry);
        }

        public static Tollgate_Proto parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static Tollgate_Proto parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Tollgate_Proto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static Tollgate_Proto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Tollgate_Proto> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return TollgateProtobuf.internal_static_Tollgate_Proto_fieldAccessorTable
                .ensureFieldAccessorsInitialized(Tollgate_Proto.class, Builder.class);
        }

        /**
         * <code>string TollgateID = 1;</code>
         */
        public String getTollgateID() {
            Object ref = tollgateID_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                tollgateID_ = s;
                return s;
            }
        }

        /**
         * <code>string TollgateID = 1;</code>
         */
        public com.google.protobuf.ByteString getTollgateIDBytes() {
            Object ref = tollgateID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                tollgateID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Name = 2;</code>
         */
        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string Name = 2;</code>
         */
        public com.google.protobuf.ByteString getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>double Longitude = 3;</code>
         */
        public double getLongitude() {
            return longitude_;
        }

        /**
         * <code>double Latitude = 4;</code>
         */
        public double getLatitude() {
            return latitude_;
        }

        /**
         * <code>string PlaceCode = 5;</code>
         */
        public String getPlaceCode() {
            Object ref = placeCode_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                placeCode_ = s;
                return s;
            }
        }

        /**
         * <code>string PlaceCode = 5;</code>
         */
        public com.google.protobuf.ByteString getPlaceCodeBytes() {
            Object ref = placeCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                placeCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Place = 6;</code>
         */
        public String getPlace() {
            Object ref = place_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                place_ = s;
                return s;
            }
        }

        /**
         * <code>string Place = 6;</code>
         */
        public com.google.protobuf.ByteString getPlaceBytes() {
            Object ref = place_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                place_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string Status = 7;</code>
         */
        public String getStatus() {
            Object ref = status_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                status_ = s;
                return s;
            }
        }

        /**
         * <code>string Status = 7;</code>
         */
        public com.google.protobuf.ByteString getStatusBytes() {
            Object ref = status_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                status_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>string TollgateCat = 8;</code>
         */
        public String getTollgateCat() {
            Object ref = tollgateCat_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                tollgateCat_ = s;
                return s;
            }
        }

        /**
         * <code>string TollgateCat = 8;</code>
         */
        public com.google.protobuf.ByteString getTollgateCatBytes() {
            Object ref = tollgateCat_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                tollgateCat_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int32 TollgateCat2 = 9;</code>
         */
        public int getTollgateCat2() {
            return tollgateCat2_;
        }

        /**
         * <code>int32 LaneNum = 10;</code>
         */
        public int getLaneNum() {
            return laneNum_;
        }

        /**
         * <code>string OrgCode = 11;</code>
         */
        public String getOrgCode() {
            Object ref = orgCode_;
            if (ref instanceof String) {
                return (String)ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                String s = bs.toStringUtf8();
                orgCode_ = s;
                return s;
            }
        }

        /**
         * <code>string OrgCode = 11;</code>
         */
        public com.google.protobuf.ByteString getOrgCodeBytes() {
            Object ref = orgCode_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                orgCode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString)ref;
            }
        }

        /**
         * <code>int64 ActiveTime = 12;</code>
         */
        public long getActiveTime() {
            return activeTime_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getTollgateIDBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tollgateID_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (longitude_ != 0D) {
                output.writeDouble(3, longitude_);
            }
            if (latitude_ != 0D) {
                output.writeDouble(4, latitude_);
            }
            if (!getPlaceCodeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, placeCode_);
            }
            if (!getPlaceBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, place_);
            }
            if (!getStatusBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, status_);
            }
            if (!getTollgateCatBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tollgateCat_);
            }
            if (tollgateCat2_ != 0) {
                output.writeInt32(9, tollgateCat2_);
            }
            if (laneNum_ != 0) {
                output.writeInt32(10, laneNum_);
            }
            if (!getOrgCodeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 11, orgCode_);
            }
            if (activeTime_ != 0L) {
                output.writeInt64(12, activeTime_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!getTollgateIDBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tollgateID_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (longitude_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(3, longitude_);
            }
            if (latitude_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(4, latitude_);
            }
            if (!getPlaceCodeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, placeCode_);
            }
            if (!getPlaceBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, place_);
            }
            if (!getStatusBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, status_);
            }
            if (!getTollgateCatBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tollgateCat_);
            }
            if (tollgateCat2_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(9, tollgateCat2_);
            }
            if (laneNum_ != 0) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(10, laneNum_);
            }
            if (!getOrgCodeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, orgCode_);
            }
            if (activeTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream.computeInt64Size(12, activeTime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Tollgate_Proto)) {
                return super.equals(obj);
            }
            Tollgate_Proto other = (Tollgate_Proto)obj;

            boolean result = true;
            result = result && getTollgateID().equals(other.getTollgateID());
            result = result && getName().equals(other.getName());
            result =
                result && (Double.doubleToLongBits(getLongitude()) == Double.doubleToLongBits(other.getLongitude()));
            result = result && (Double.doubleToLongBits(getLatitude()) == Double.doubleToLongBits(other.getLatitude()));
            result = result && getPlaceCode().equals(other.getPlaceCode());
            result = result && getPlace().equals(other.getPlace());
            result = result && getStatus().equals(other.getStatus());
            result = result && getTollgateCat().equals(other.getTollgateCat());
            result = result && (getTollgateCat2() == other.getTollgateCat2());
            result = result && (getLaneNum() == other.getLaneNum());
            result = result && getOrgCode().equals(other.getOrgCode());
            result = result && (getActiveTime() == other.getActiveTime());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TOLLGATEID_FIELD_NUMBER;
            hash = (53 * hash) + getTollgateID().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getLongitude()));
            hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(Double.doubleToLongBits(getLatitude()));
            hash = (37 * hash) + PLACECODE_FIELD_NUMBER;
            hash = (53 * hash) + getPlaceCode().hashCode();
            hash = (37 * hash) + PLACE_FIELD_NUMBER;
            hash = (53 * hash) + getPlace().hashCode();
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + getStatus().hashCode();
            hash = (37 * hash) + TOLLGATECAT_FIELD_NUMBER;
            hash = (53 * hash) + getTollgateCat().hashCode();
            hash = (37 * hash) + TOLLGATECAT2_FIELD_NUMBER;
            hash = (53 * hash) + getTollgateCat2();
            hash = (37 * hash) + LANENUM_FIELD_NUMBER;
            hash = (53 * hash) + getLaneNum();
            hash = (37 * hash) + ORGCODE_FIELD_NUMBER;
            hash = (53 * hash) + getOrgCode().hashCode();
            hash = (37 * hash) + ACTIVETIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getActiveTime());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<Tollgate_Proto> getParserForType() {
            return PARSER;
        }

        public Tollgate_Proto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code Tollgate_Proto}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Tollgate_Proto)
            Tollgate_ProtoOrBuilder {
            private Object tollgateID_ = "";
            private Object name_ = "";
            private double longitude_;
            private double latitude_;
            private Object placeCode_ = "";
            private Object place_ = "";
            private Object status_ = "";
            private Object tollgateCat_ = "";
            private int tollgateCat2_;
            private int laneNum_;
            private Object orgCode_ = "";
            private long activeTime_;

            // Construct using com.kedacom.ctsp.cvf.viid.common.protobuf.TollgateProtobuf.Tollgate_Proto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return TollgateProtobuf.internal_static_Tollgate_Proto_descriptor;
            }

            protected FieldAccessorTable internalGetFieldAccessorTable() {
                return TollgateProtobuf.internal_static_Tollgate_Proto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(Tollgate_Proto.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                tollgateID_ = "";

                name_ = "";

                longitude_ = 0D;

                latitude_ = 0D;

                placeCode_ = "";

                place_ = "";

                status_ = "";

                tollgateCat_ = "";

                tollgateCat2_ = 0;

                laneNum_ = 0;

                orgCode_ = "";

                activeTime_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return TollgateProtobuf.internal_static_Tollgate_Proto_descriptor;
            }

            public Tollgate_Proto getDefaultInstanceForType() {
                return Tollgate_Proto.getDefaultInstance();
            }

            public Tollgate_Proto build() {
                Tollgate_Proto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Tollgate_Proto buildPartial() {
                Tollgate_Proto result = new Tollgate_Proto(this);
                result.tollgateID_ = tollgateID_;
                result.name_ = name_;
                result.longitude_ = longitude_;
                result.latitude_ = latitude_;
                result.placeCode_ = placeCode_;
                result.place_ = place_;
                result.status_ = status_;
                result.tollgateCat_ = tollgateCat_;
                result.tollgateCat2_ = tollgateCat2_;
                result.laneNum_ = laneNum_;
                result.orgCode_ = orgCode_;
                result.activeTime_ = activeTime_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder)super.clone();
            }

            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.setField(field, value);
            }

            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder)super.clearField(field);
            }

            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder)super.clearOneof(oneof);
            }

            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                Object value) {
                return (Builder)super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
                return (Builder)super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Tollgate_Proto) {
                    return mergeFrom((Tollgate_Proto)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Tollgate_Proto other) {
                if (other == Tollgate_Proto.getDefaultInstance())
                    return this;
                if (!other.getTollgateID().isEmpty()) {
                    tollgateID_ = other.tollgateID_;
                    onChanged();
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.getLongitude() != 0D) {
                    setLongitude(other.getLongitude());
                }
                if (other.getLatitude() != 0D) {
                    setLatitude(other.getLatitude());
                }
                if (!other.getPlaceCode().isEmpty()) {
                    placeCode_ = other.placeCode_;
                    onChanged();
                }
                if (!other.getPlace().isEmpty()) {
                    place_ = other.place_;
                    onChanged();
                }
                if (!other.getStatus().isEmpty()) {
                    status_ = other.status_;
                    onChanged();
                }
                if (!other.getTollgateCat().isEmpty()) {
                    tollgateCat_ = other.tollgateCat_;
                    onChanged();
                }
                if (other.getTollgateCat2() != 0) {
                    setTollgateCat2(other.getTollgateCat2());
                }
                if (other.getLaneNum() != 0) {
                    setLaneNum(other.getLaneNum());
                }
                if (!other.getOrgCode().isEmpty()) {
                    orgCode_ = other.orgCode_;
                    onChanged();
                }
                if (other.getActiveTime() != 0L) {
                    setActiveTime(other.getActiveTime());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                Tollgate_Proto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Tollgate_Proto)e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public String getTollgateID() {
                Object ref = tollgateID_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    tollgateID_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public Builder setTollgateID(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                tollgateID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public com.google.protobuf.ByteString getTollgateIDBytes() {
                Object ref = tollgateID_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    tollgateID_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public Builder setTollgateIDBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                tollgateID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string TollgateID = 1;</code>
             */
            public Builder clearTollgateID() {

                tollgateID_ = getDefaultInstance().getTollgateID();
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 2;</code>
             */
            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Name = 2;</code>
             */
            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 2;</code>
             */
            public com.google.protobuf.ByteString getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Name = 2;</code>
             */
            public Builder setNameBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Name = 2;</code>
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>double Longitude = 3;</code>
             */
            public double getLongitude() {
                return longitude_;
            }

            /**
             * <code>double Longitude = 3;</code>
             */
            public Builder setLongitude(double value) {

                longitude_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double Longitude = 3;</code>
             */
            public Builder clearLongitude() {

                longitude_ = 0D;
                onChanged();
                return this;
            }

            /**
             * <code>double Latitude = 4;</code>
             */
            public double getLatitude() {
                return latitude_;
            }

            /**
             * <code>double Latitude = 4;</code>
             */
            public Builder setLatitude(double value) {

                latitude_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double Latitude = 4;</code>
             */
            public Builder clearLatitude() {

                latitude_ = 0D;
                onChanged();
                return this;
            }

            /**
             * <code>string PlaceCode = 5;</code>
             */
            public String getPlaceCode() {
                Object ref = placeCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    placeCode_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string PlaceCode = 5;</code>
             */
            public Builder setPlaceCode(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                placeCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string PlaceCode = 5;</code>
             */
            public com.google.protobuf.ByteString getPlaceCodeBytes() {
                Object ref = placeCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    placeCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string PlaceCode = 5;</code>
             */
            public Builder setPlaceCodeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                placeCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string PlaceCode = 5;</code>
             */
            public Builder clearPlaceCode() {

                placeCode_ = getDefaultInstance().getPlaceCode();
                onChanged();
                return this;
            }

            /**
             * <code>string Place = 6;</code>
             */
            public String getPlace() {
                Object ref = place_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    place_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Place = 6;</code>
             */
            public Builder setPlace(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                place_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Place = 6;</code>
             */
            public com.google.protobuf.ByteString getPlaceBytes() {
                Object ref = place_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    place_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Place = 6;</code>
             */
            public Builder setPlaceBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                place_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Place = 6;</code>
             */
            public Builder clearPlace() {

                place_ = getDefaultInstance().getPlace();
                onChanged();
                return this;
            }

            /**
             * <code>string Status = 7;</code>
             */
            public String getStatus() {
                Object ref = status_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    status_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string Status = 7;</code>
             */
            public Builder setStatus(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Status = 7;</code>
             */
            public com.google.protobuf.ByteString getStatusBytes() {
                Object ref = status_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    status_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string Status = 7;</code>
             */
            public Builder setStatusBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string Status = 7;</code>
             */
            public Builder clearStatus() {

                status_ = getDefaultInstance().getStatus();
                onChanged();
                return this;
            }

            /**
             * <code>string TollgateCat = 8;</code>
             */
            public String getTollgateCat() {
                Object ref = tollgateCat_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    tollgateCat_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string TollgateCat = 8;</code>
             */
            public Builder setTollgateCat(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                tollgateCat_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string TollgateCat = 8;</code>
             */
            public com.google.protobuf.ByteString getTollgateCatBytes() {
                Object ref = tollgateCat_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    tollgateCat_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string TollgateCat = 8;</code>
             */
            public Builder setTollgateCatBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                tollgateCat_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string TollgateCat = 8;</code>
             */
            public Builder clearTollgateCat() {

                tollgateCat_ = getDefaultInstance().getTollgateCat();
                onChanged();
                return this;
            }

            /**
             * <code>int32 TollgateCat2 = 9;</code>
             */
            public int getTollgateCat2() {
                return tollgateCat2_;
            }

            /**
             * <code>int32 TollgateCat2 = 9;</code>
             */
            public Builder setTollgateCat2(int value) {

                tollgateCat2_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 TollgateCat2 = 9;</code>
             */
            public Builder clearTollgateCat2() {

                tollgateCat2_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>int32 LaneNum = 10;</code>
             */
            public int getLaneNum() {
                return laneNum_;
            }

            /**
             * <code>int32 LaneNum = 10;</code>
             */
            public Builder setLaneNum(int value) {

                laneNum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 LaneNum = 10;</code>
             */
            public Builder clearLaneNum() {

                laneNum_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public String getOrgCode() {
                Object ref = orgCode_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString)ref;
                    String s = bs.toStringUtf8();
                    orgCode_ = s;
                    return s;
                } else {
                    return (String)ref;
                }
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public Builder setOrgCode(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                orgCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public com.google.protobuf.ByteString getOrgCodeBytes() {
                Object ref = orgCode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String)ref);
                    orgCode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString)ref;
                }
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public Builder setOrgCodeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                orgCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string OrgCode = 11;</code>
             */
            public Builder clearOrgCode() {

                orgCode_ = getDefaultInstance().getOrgCode();
                onChanged();
                return this;
            }

            /**
             * <code>int64 ActiveTime = 12;</code>
             */
            public long getActiveTime() {
                return activeTime_;
            }

            /**
             * <code>int64 ActiveTime = 12;</code>
             */
            public Builder setActiveTime(long value) {

                activeTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 ActiveTime = 12;</code>
             */
            public Builder clearActiveTime() {

                activeTime_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:Tollgate_Proto)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
